create table ASS_HALFCARRY_ACCOUNT_CORR
(
 DT VARCHAR2 ( 10) NOT NULL,
 SYSMOMENT DATE NOT NULL,
 HALFCARRY_CODE VARCHAR2(100) NOT NULL,
 ACCOUNT_CODE  VARCHAR2(50) NOT NULL,
 REC_STATUS CHAR(1) NOT NULL,
 REC_UNLOAD NUMBER(1),
 REC_PROCESS NUMBER(1),
 ID_FILE NUMBER(10)
)
tablespace MSFO_DATA
/
comment on column ASS_HALFCARRY_ACCOUNT_CORR.DT is 'Дата открытия'
/
comment on column ASS_HALFCARRY_ACCOUNT_CORR.halfcarry_code is 'Код полупроводки'
/
comment on column ASS_HALFCARRY_ACCOUNT_CORR.account_code is 'Код лицевого счета'
/
comment on table ASS_HALFCARRY_ACCOUNT_CORR is 'Корреспондирующие счета для полупроводки'
/

ALTER TABLE ASS_HALFCARRY_ACCOUNT_CORR
ADD CONSTRAINT pk_ASS_HALFCARRY_ACC_CORR PRIMARY KEY(HALFCARRY_CODE)
USING INDEX TABLESPACE MSFO_INDEX;

create bitmap index idx_ASS_HALFCARRY_ACC_CORR_unl
    on ASS_HALFCARRY_ACCOUNT_CORR( rec_unload)
    TABLESPACE MSFO_INDEX;

create index idx_ASS_HALFCARRY_ACC_CORR_dt
    on ASS_HALFCARRY_ACCOUNT_CORR( dt)
    TABLESPACE MSFO_INDEX;

ALTER TABLE ASS_HALFCARRY_ACCOUNT_CORR
ADD CONSTRAINT ASS_HALFCARRY_ACC_CORR_id_file
 FOREIGN KEY(id_file)
REFERENCES bp_fct_files(ID_FILE)
/

ALTER TABLE ASS_HALFCARRY_ACCOUNT_CORR
ADD CONSTRAINT fk_ASS_HALFCARRY_ACC_CORR_code
 FOREIGN KEY(halfcarry_code)
REFERENCES fct_halfcarry(code)
/

ALTER TABLE ASS_HALFCARRY_ACCOUNT_CORR
ADD CONSTRAINT fk_ASS_HALFCARRY_ACC_CORR_acc
 FOREIGN KEY(account_code)
REFERENCES det_account(code)
/

