-- Создание владельца схемы
CREATE USER "MSFO"  PROFILE "DEFAULT" 
    IDENTIFIED BY "MSFO" DEFAULT TABLESPACE "MSFO_DATA" 
    TEMPORARY TABLESPACE "TEMP" 
    ACCOUNT UNLOCK;
GRANT "CONNECT" TO "MSFO";
GRANT "RESOURCE" TO "MSFO";
grant create public synonym to msfo;
ALTER USER MSFO DEFAULT ROLE ALL;
