-- Создание табличных пространств
CREATE TABLESPACE "MSFO_DATA" 
    LOGGING 
    DATAFILE 'F:\ORACLE\ORADATA\DEV\MSFO_DATA1.ora' SIZE 5M 
    AUTOEXTEND 
    ON NEXT  64M MAXSIZE UNLIMITED EXTENT MANAGEMENT LOCAL 
    UNIFORM SIZE 4M;

CREATE TABLESPACE "MSFO_INDEX" 
    LOGGING 
    DATAFILE 'F:\ORACLE\ORADATA\DEV\MSFO_INDEX1.ora' SIZE 5M 
    AUTOEXTEND 
    ON NEXT  64M MAXSIZE UNLIMITED EXTENT MANAGEMENT LOCAL 
    UNIFORM SIZE 4M;

CREATE TABLESPACE "MSFO_NSI" 
    LOGGING 
    DATAFILE 'F:\ORACLE\ORADATA\DEV\MSFO_NSI1.ora' SIZE 5M 
    AUTOEXTEND 
    ON NEXT 4M MAXSIZE UNLIMITED EXTENT MANAGEMENT LOCAL 
    UNIFORM SIZE 64K;
