ALTER TABLE ass_account_balance
ADD CONSTRAINT pk_ass_account_balance 
PRIMARY KEY(system_code_system, CODE_DEPARTMENT_DEPARTMENT, account_number_account)
USING INDEX TABLESPACE MSFO_INDEX;

ALTER TABLE ass_account_cat
ADD CONSTRAINT pk_ass_account_cat 
PRIMARY KEY(system_code_system, CODE_DEPARTMENT_DEPARTMENT, account_number_account)
USING INDEX TABLESPACE MSFO_INDEX;

ALTER TABLE ass_bank_department
ADD CONSTRAINT pk_ass_bank_department PRIMARY KEY(code_department_child)
USING INDEX TABLESPACE MSFO_NSI;

ALTER TABLE ass_cfa_account
ADD CONSTRAINT pk_ass_cfa_account 
PRIMARY KEY(system_code_system, CODE_DEPARTMENT_DEPARTMENT, account_number_account)
USING INDEX TABLESPACE MSFO_INDEX;

ALTER TABLE ass_curr_groupcurr
ADD CONSTRAINT pk_ass_curr_groupcurr PRIMARY KEY(CURR_CODE_TXT_CURRENCY)
USING INDEX TABLESPACE MSFO_NSI;

ALTER TABLE ass_det_account
ADD CONSTRAINT pk_ass_det_account 
PRIMARY KEY(system_code_system_child, CODE_DEPARTMENT_DEPARTME_CHILD, account_number_account_chi)
USING INDEX TABLESPACE MSFO_INDEX;

ALTER TABLE ass_det_balance
ADD CONSTRAINT pk_ass_det_balance PRIMARY KEY(balance_code_child)
USING INDEX TABLESPACE MSFO_NSI;

ALTER TABLE ass_det_okonh
ADD CONSTRAINT pk_ass_det_okonh PRIMARY KEY(okonh_code_child)
USING INDEX TABLESPACE MSFO_NSI;

ALTER TABLE ass_det_okved
ADD CONSTRAINT pk_ass_det_okved PRIMARY KEY(okved_code_child)
USING INDEX TABLESPACE MSFO_NSI;

ALTER TABLE ass_subject_cat
ADD CONSTRAINT pk_ass_subject_cat 
PRIMARY KEY(system_code_system, CODE_DEPARTMENT_DEPARTMENT, code_subject_subject, SUBJECT_CAT_CODE_SUBJECT_CAT)
USING INDEX TABLESPACE MSFO_DATA;

ALTER TABLE det_acc_ass_kind
ADD CONSTRAINT pk_det_acc_ass_kind PRIMARY KEY(ACC_ASS_KIND_CODE)
USING INDEX TABLESPACE MSFO_NSI;

ALTER TABLE det_account
ADD CONSTRAINT pk_det_account PRIMARY KEY(SYSTEM_CODE_SYSTEM, CODE_DEPARTMENT_DEPARTMENT, ACCOUNT_NUMBER)
USING INDEX TABLESPACE MSFO_INDEX;

ALTER TABLE det_account_cat
ADD CONSTRAINT pk_det_account_cat PRIMARY KEY(ACCOUNT_CAT_CODE)
USING INDEX TABLESPACE MSFO_NSI;

ALTER TABLE det_account_cat_val
ADD CONSTRAINT pk_det_account_cat_val 
PRIMARY KEY(ACCOUNT_CAT_CODE_ACCOUNT_CAT, ACCOUNT_CAT_VAL_CODE)
USING INDEX TABLESPACE MSFO_NSI;

ALTER TABLE det_balance
ADD CONSTRAINT pk_det_balance PRIMARY KEY(balance_code)
USING INDEX TABLESPACE MSFO_NSI;

ALTER TABLE det_carry_cat
ADD CONSTRAINT pk_det_carry_cat PRIMARY KEY(carry_cat_code)
USING INDEX TABLESPACE MSFO_NSI;

ALTER TABLE det_carry_cat_val
ADD CONSTRAINT pk_det_carry_cat_val PRIMARY KEY(carry_cat_code_carry_cat, CARRY_CAT_VAL_CODE)
USING INDEX TABLESPACE MSFO_NSI;

ALTER TABLE det_cfa
ADD CONSTRAINT pk_det_cfa PRIMARY KEY(code)
USING INDEX TABLESPACE MSFO_NSI;

ALTER TABLE det_chapter
ADD CONSTRAINT pk_det_chapter PRIMARY KEY(chapter_code)
USING INDEX TABLESPACE MSFO_NSI;

ALTER TABLE det_country
ADD CONSTRAINT pk_det_country PRIMARY KEY(country_code_num)
USING INDEX TABLESPACE MSFO_NSI;

ALTER TABLE det_currency
ADD CONSTRAINT pk_det_currency PRIMARY KEY(curr_code_txt)
USING INDEX TABLESPACE MSFO_NSI;

ALTER TABLE det_currencygroup
ADD CONSTRAINT pk_det_currencygroup PRIMARY KEY(code)
USING INDEX TABLESPACE MSFO_NSI;

ALTER TABLE det_department
ADD CONSTRAINT pk_det_department PRIMARY KEY(code_department)
USING INDEX TABLESPACE MSFO_NSI;

ALTER TABLE det_finstr
ADD CONSTRAINT pk_det_finstr PRIMARY KEY(finstr_code)
USING INDEX TABLESPACE MSFO_NSI;

ALTER TABLE det_juridic_person
ADD CONSTRAINT pk_det_juridic_person 
PRIMARY KEY(SYSTEM_CODE_SYSTEM, CODE_DEPARTMENT_DEPARTMENT, CODE_SUBJECT_SUBJECT)
USING INDEX TABLESPACE MSFO_INDEX;

ALTER TABLE det_okato
ADD CONSTRAINT pk_det_okato PRIMARY KEY(code)
USING INDEX TABLESPACE MSFO_NSI;

ALTER TABLE det_okonh
ADD CONSTRAINT pk_det_okonh PRIMARY KEY(okonh_code)
USING INDEX TABLESPACE MSFO_NSI;

ALTER TABLE det_okved
ADD CONSTRAINT pk_det_okved PRIMARY KEY(okved_code)
USING INDEX TABLESPACE MSFO_NSI;

ALTER TABLE DET_PHYZ_PERSON
ADD CONSTRAINT pk_det_PHYZ_PERSON 
PRIMARY KEY(SYSTEM_CODE_SYSTEM, CODE_DEPARTMENT_DEPARTMENT, CODE_SUBJECT_SUBJECT)
USING INDEX TABLESPACE MSFO_INDEX;

ALTER TABLE det_plan_bal
ADD CONSTRAINT pk_det_plan_bal PRIMARY KEY(plan_bal_code)
USING INDEX TABLESPACE MSFO_NSI;

ALTER TABLE DET_SUBJECT
ADD CONSTRAINT pk_det_subject PRIMARY KEY(SYSTEM_CODE_SYSTEM, CODE_DEPARTMENT_DEPARTMENT, CODE_SUBJECT)
USING INDEX TABLESPACE MSFO_INDEX;

ALTER TABLE DET_SUBJECT_CAT
ADD CONSTRAINT pk_det_subject_cat PRIMARY KEY(SUBJECT_CAT_CODE)
USING INDEX TABLESPACE MSFO_NSI;

ALTER TABLE DET_SUBJECT_CAT_VAL
ADD CONSTRAINT pk_det_subject_cat_val PRIMARY KEY(SUBJECT_CAT_CODE_SUBJECT_CAT, SUBJECT_CAT_VAL_CODE)
USING INDEX TABLESPACE MSFO_NSI;

ALTER TABLE DET_SUBJECTGROUP
ADD CONSTRAINT pk_det_subjectgroup PRIMARY KEY(CODE_SUBJECTGROUP)
USING INDEX TABLESPACE MSFO_NSI;

ALTER TABLE det_system
ADD CONSTRAINT pk_det_system PRIMARY KEY(system_code)
USING INDEX TABLESPACE MSFO_NSI;

ALTER TABLE det_type_rate
ADD CONSTRAINT pk_det_type_rate PRIMARY KEY(TYPE_RATE_CODE)
USING INDEX TABLESPACE MSFO_NSI;

ALTER TABLE det_typelinkgroup
ADD CONSTRAINT pk_det_typelinkgroup PRIMARY KEY(CODE_SUBJECTLINK)
USING INDEX TABLESPACE MSFO_NSI;

ALTER TABLE fct_account
ADD CONSTRAINT pk_fct_account 
PRIMARY KEY(DT, SYSTEM_CODE_SYSTEM, CODE_DEPARTMENT_DEPARTMENT, ACCOUNT_NUMBER_ACCOUNT)
USING INDEX TABLESPACE MSFO_INDEX;

ALTER TABLE fct_balance
ADD CONSTRAINT pk_fct_balance 
PRIMARY KEY(DT, CODE_DEPARTMENT_DEPARTMENT, BALANCE_CODE_BALANCE, CURR_CODE_TXT_CURRENCY)
USING INDEX TABLESPACE MSFO_INDEX;

ALTER TABLE fct_balance_cfa
ADD CONSTRAINT pk_fct_balance_cfa 
PRIMARY KEY(DT, CODE_DEPARTMENT_DEPARTMENT, BALANCE_CODE_BALANCE, CURR_CODE_TXT_CURRENCY, CODE_CFA)
USING INDEX TABLESPACE MSFO_INDEX;

ALTER TABLE fct_finstr_rate
ADD CONSTRAINT pk_fct_finstr_rate 
 PRIMARY KEY(DT, CODE_DEPARTMENT_DEPARTMENT, TYPE_RATE_CODE_TYPE_FINSTR_RAT, FINSTR_CODE_FINSTR_DENIMINATOR, FINSTR_CODE_FINSTR_NUMERATOR)
USING INDEX TABLESPACE MSFO_INDEX;

ALTER TABLE det_roleaccount_deal
ADD CONSTRAINT pk_det_roleaccount_deal PRIMARY KEY(code)
USING INDEX TABLESPACE MSFO_NSI;

ALTER TABLE fct_carry
ADD CONSTRAINT pk_fct_carry PRIMARY KEY(system_code_system_debet, code)
USING INDEX TABLESPACE MSFO_INDEX;

ALTER TABLE fct_halfcarry
ADD CONSTRAINT pk_fct_halfcarry PRIMARY KEY(system_code_system, code)
USING INDEX TABLESPACE MSFO_INDEX;

ALTER TABLE fct_payment
ADD CONSTRAINT pk_fct_payment PRIMARY KEY(system_code_subject, code)
USING INDEX TABLESPACE MSFO_INDEX;

ALTER TABLE ass_carry_cat
ADD CONSTRAINT pk_ass_carry_cat PRIMARY KEY(CODE_CARRY, CARRY_CAT_CODE_CARRY_CAT)
USING INDEX TABLESPACE MSFO_INDEX;

ALTER TABLE det_typeattr
ADD CONSTRAINT pk_det_typeattr PRIMARY KEY(code)
USING INDEX TABLESPACE MSFO_NSI;

ALTER TABLE fct_subjattr
ADD CONSTRAINT pk_fct_subjattr PRIMARY KEY(SYSTEM_CODE_SYSTEM_SUBJ, CODE_DEPARTMENT_DEPARTM_SUBJ, CODE_SUBJECT_SUBJECT, CODE_TYPEATTR)
USING INDEX TABLESPACE MSFO_NSI;
