create table FCT_ASSREPAYSCHEDULE
(
 CODE VARCHAR2(100) NOT NULL,
 TYPEREPAYASS NUMBER(1) NOT NULL,
 REPAYSUM NUMBER(24,3),
 DT VARCHAR2(10) NOT NULL,
 SYSMOMENT DATE,
 ASSET_CODE VARCHAR2(100) NOT NULL,
 REC_STATUS CHAR(1) NOT NULL,
 REC_UNLOAD NUMBER(1),
 REC_PROCESS NUMBER(1),
 ID_FILE NUMBER(16)
)
tablespace MSFO_DATA
/

comment on column FCT_ASSREPAYSCHEDULE.CODE IS 'Код строки графика';
comment on column FCT_ASSREPAYSCHEDULE.TYPEREPAYASS IS 'Тип строки';
comment on column FCT_ASSREPAYSCHEDULE.REPAYSUM IS 'Сумма платежа';
comment on column FCT_ASSREPAYSCHEDULE.DT IS 'Дата открытия';
comment on column FCT_ASSREPAYSCHEDULE.ASSET_CODE IS 'Код основного средства';

comment on table FCT_ASSREPAYSCHEDULE is 'Основные средства';

ALTER TABLE FCT_ASSREPAYSCHEDULE
ADD CONSTRAINT pk_FCT_ASSREPAYSCHEDULE 
PRIMARY KEY(code)
USING INDEX TABLESPACE MSFO_INDEX;

create bitmap index idx_FCT_ASSREPAYSCHEDULE_unl
    on FCT_ASSREPAYSCHEDULE( rec_unload)
    TABLESPACE MSFO_INDEX;

ALTER TABLE FCT_ASSREPAYSCHEDULE
ADD CONSTRAINT fk_FCT_ASSREPAYSCH_id_file
FOREIGN KEY(id_file)
REFERENCES bp_fct_files(ID_FILE)
/

ALTER TABLE FCT_ASSREPAYSCHEDULE
ADD CONSTRAINT fk_FCT_ASSREPAYSCH_asset_code
FOREIGN KEY(asset_code)
REFERENCES fct_asset(code)
/
