INSERT INTO DET_COUNTRY ( COUNTRY_NAME, COUNTRY_CODE_NUM, PRIZN_RS, DT, REC_STATUS, REC_UNLOAD,
REC_PROCESS, ID_FILE ) VALUES ( 
'Œ—“–Œ¬ Ã›Õ', 833, '0', '01-01-1980', '0', 0, 1, NULL); 
INSERT INTO DET_COUNTRY ( COUNTRY_NAME, COUNTRY_CODE_NUM, PRIZN_RS, DT, REC_STATUS, REC_UNLOAD,
REC_PROCESS, ID_FILE ) VALUES ( 
'Ã≈∆ƒ”Õ¿–.Œ–√¿Õ»«¿÷»ﬂ', 998, '0', '01-01-1980', '0', 0, 1, NULL); 
INSERT INTO DET_COUNTRY ( COUNTRY_NAME, COUNTRY_CODE_NUM, PRIZN_RS, DT, REC_STATUS, REC_UNLOAD,
REC_PROCESS, ID_FILE ) VALUES ( 
'Ã¿…Œ““¿', 175, '0', '01-01-1980', '0', 0, 1, NULL); 
INSERT INTO DET_COUNTRY ( COUNTRY_NAME, COUNTRY_CODE_NUM, PRIZN_RS, DT, REC_STATUS, REC_UNLOAD,
REC_PROCESS, ID_FILE ) VALUES ( 
'›–»“–≈ﬂ', 232, '0', '01-01-1980', '0', 0, 1, NULL); 
INSERT INTO DET_COUNTRY ( COUNTRY_NAME, COUNTRY_CODE_NUM, PRIZN_RS, DT, REC_STATUS, REC_UNLOAD,
REC_PROCESS, ID_FILE ) VALUES ( 
'Ã¿ ≈ƒŒÕ»ﬂ', 807, '0', '01-01-1980', '0', 0, 1, NULL); 
INSERT INTO DET_COUNTRY ( COUNTRY_NAME, COUNTRY_CODE_NUM, PRIZN_RS, DT, REC_STATUS, REC_UNLOAD,
REC_PROCESS, ID_FILE ) VALUES ( 
'ﬁ√Œ—À¿¬»ﬂ', 891, '0', '01-01-1980', '0', 0, 1, NULL); 
INSERT INTO DET_COUNTRY ( COUNTRY_NAME, COUNTRY_CODE_NUM, PRIZN_RS, DT, REC_STATUS, REC_UNLOAD,
REC_PROCESS, ID_FILE ) VALUES ( 
'¡Œ—Õ»ﬂ » √≈–÷≈√Œ¬»Õ¿', 70, '0', '01-01-1980', '0', 0, 1, NULL); 
INSERT INTO DET_COUNTRY ( COUNTRY_NAME, COUNTRY_CODE_NUM, PRIZN_RS, DT, REC_STATUS, REC_UNLOAD,
REC_PROCESS, ID_FILE ) VALUES ( 
'—ÀŒ¬¿ »ﬂ', 703, '0', '01-01-1980', '0', 0, 1, NULL); 
INSERT INTO DET_COUNTRY ( COUNTRY_NAME, COUNTRY_CODE_NUM, PRIZN_RS, DT, REC_STATUS, REC_UNLOAD,
REC_PROCESS, ID_FILE ) VALUES ( 
'◊≈’»ﬂ', 203, '0', '01-01-1980', '0', 0, 1, NULL); 
INSERT INTO DET_COUNTRY ( COUNTRY_NAME, COUNTRY_CODE_NUM, PRIZN_RS, DT, REC_STATUS, REC_UNLOAD,
REC_PROCESS, ID_FILE ) VALUES ( 
'’Œ–¬¿“»ﬂ', 191, '0', '01-01-1980', '0', 0, 1, NULL); 
INSERT INTO DET_COUNTRY ( COUNTRY_NAME, COUNTRY_CODE_NUM, PRIZN_RS, DT, REC_STATUS, REC_UNLOAD,
REC_PROCESS, ID_FILE ) VALUES ( 
'—ÀŒ¬≈Õ»ﬂ', 705, '0', '01-01-1980', '0', 0, 1, NULL); 
INSERT INTO DET_COUNTRY ( COUNTRY_NAME, COUNTRY_CODE_NUM, PRIZN_RS, DT, REC_STATUS, REC_UNLOAD,
REC_PROCESS, ID_FILE ) VALUES ( 
'ﬂœŒÕ»ﬂ', 392, '1', '01-01-1980', '0', 0, 1, NULL); 
INSERT INTO DET_COUNTRY ( COUNTRY_NAME, COUNTRY_CODE_NUM, PRIZN_RS, DT, REC_STATUS, REC_UNLOAD,
REC_PROCESS, ID_FILE ) VALUES ( 
'ﬂÃ¿… ¿', 388, '0', '01-01-1980', '0', 0, 1, NULL); 
INSERT INTO DET_COUNTRY ( COUNTRY_NAME, COUNTRY_CODE_NUM, PRIZN_RS, DT, REC_STATUS, REC_UNLOAD,
REC_PROCESS, ID_FILE ) VALUES ( 
'ﬁ¿–', 710, '0', '01-01-1980', '0', 0, 1, NULL); 
INSERT INTO DET_COUNTRY ( COUNTRY_NAME, COUNTRY_CODE_NUM, PRIZN_RS, DT, REC_STATUS, REC_UNLOAD,
REC_PROCESS, ID_FILE ) VALUES ( 
'›‘»Œœ»ﬂ', 231, '0', '01-01-1980', '0', 0, 1, NULL); 
INSERT INTO DET_COUNTRY ( COUNTRY_NAME, COUNTRY_CODE_NUM, PRIZN_RS, DT, REC_STATUS, REC_UNLOAD,
REC_PROCESS, ID_FILE ) VALUES ( 
'›—“ŒÕ»ﬂ', 233, '0', '01-01-1980', '0', 0, 1, NULL); 
INSERT INTO DET_COUNTRY ( COUNTRY_NAME, COUNTRY_CODE_NUM, PRIZN_RS, DT, REC_STATUS, REC_UNLOAD,
REC_PROCESS, ID_FILE ) VALUES ( 
'› ¬¿“Œ–»¿À‹Õ¿ﬂ √¬»Õ≈ﬂ', 226, '0', '01-01-1980', '0', 0, 1, NULL); 
INSERT INTO DET_COUNTRY ( COUNTRY_NAME, COUNTRY_CODE_NUM, PRIZN_RS, DT, REC_STATUS, REC_UNLOAD,
REC_PROCESS, ID_FILE ) VALUES ( 
'› ¬¿ƒŒ–', 218, '0', '01-01-1980', '0', 0, 1, NULL); 
INSERT INTO DET_COUNTRY ( COUNTRY_NAME, COUNTRY_CODE_NUM, PRIZN_RS, DT, REC_STATUS, REC_UNLOAD,
REC_PROCESS, ID_FILE ) VALUES ( 
'ÿ–»-À¿Õ ¿', 144, '0', '01-01-1980', '0', 0, 1, NULL); 
INSERT INTO DET_COUNTRY ( COUNTRY_NAME, COUNTRY_CODE_NUM, PRIZN_RS, DT, REC_STATUS, REC_UNLOAD,
REC_PROCESS, ID_FILE ) VALUES ( 
'ÿœ»÷¡≈–√≈Õ Œ—“–Œ¬¿', 744, '0', '01-01-1980', '0', 0, 1, NULL); 
INSERT INTO DET_COUNTRY ( COUNTRY_NAME, COUNTRY_CODE_NUM, PRIZN_RS, DT, REC_STATUS, REC_UNLOAD,
REC_PROCESS, ID_FILE ) VALUES ( 
'ÿ¬≈÷»ﬂ', 752, '1', '01-01-1980', '0', 0, 1, NULL); 
INSERT INTO DET_COUNTRY ( COUNTRY_NAME, COUNTRY_CODE_NUM, PRIZN_RS, DT, REC_STATUS, REC_UNLOAD,
REC_PROCESS, ID_FILE ) VALUES ( 
'ÿ¬≈…÷¿–»ﬂ', 756, '1', '01-01-1980', '0', 0, 1, NULL); 
INSERT INTO DET_COUNTRY ( COUNTRY_NAME, COUNTRY_CODE_NUM, PRIZN_RS, DT, REC_STATUS, REC_UNLOAD,
REC_PROCESS, ID_FILE ) VALUES ( 
'◊»À»', 152, '0', '01-01-1980', '0', 0, 1, NULL); 
INSERT INTO DET_COUNTRY ( COUNTRY_NAME, COUNTRY_CODE_NUM, PRIZN_RS, DT, REC_STATUS, REC_UNLOAD,
REC_PROCESS, ID_FILE ) VALUES ( 
'◊¿ƒ', 148, '0', '01-01-1980', '0', 0, 1, NULL); 
INSERT INTO DET_COUNTRY ( COUNTRY_NAME, COUNTRY_CODE_NUM, PRIZN_RS, DT, REC_STATUS, REC_UNLOAD,
REC_PROCESS, ID_FILE ) VALUES ( 
'÷≈Õ“–¿À‹ÕŒ-¿‘–» ¿Õ— ¿ﬂ –≈—œ”¡À» ', 140, '0', '01-01-1980', '0', 0, 1, NULL); 
INSERT INTO DET_COUNTRY ( COUNTRY_NAME, COUNTRY_CODE_NUM, PRIZN_RS, DT, REC_STATUS, REC_UNLOAD,
REC_PROCESS, ID_FILE ) VALUES ( 
'’≈–ƒ » Ã¿ ƒŒÕ¿À‹ƒ', 334, '0', '01-01-1980', '0', 0, 1, NULL); 
INSERT INTO DET_COUNTRY ( COUNTRY_NAME, COUNTRY_CODE_NUM, PRIZN_RS, DT, REC_STATUS, REC_UNLOAD,
REC_PROCESS, ID_FILE ) VALUES ( 
'‘–¿Õ÷»ﬂ', 250, '1', '01-01-1980', '0', 0, 1, NULL); 
INSERT INTO DET_COUNTRY ( COUNTRY_NAME, COUNTRY_CODE_NUM, PRIZN_RS, DT, REC_STATUS, REC_UNLOAD,
REC_PROCESS, ID_FILE ) VALUES ( 
'‘–¿Õ÷”«— »≈ ﬁ∆Õ€≈ “≈––»“Œ–»»', 260, '0', '01-01-1980', '0', 0, 1, NULL); 
INSERT INTO DET_COUNTRY ( COUNTRY_NAME, COUNTRY_CODE_NUM, PRIZN_RS, DT, REC_STATUS, REC_UNLOAD,
REC_PROCESS, ID_FILE ) VALUES ( 
'√¬»¿Õ¿', 254, '0', '01-01-1980', '0', 0, 1, NULL); 
INSERT INTO DET_COUNTRY ( COUNTRY_NAME, COUNTRY_CODE_NUM, PRIZN_RS, DT, REC_STATUS, REC_UNLOAD,
REC_PROCESS, ID_FILE ) VALUES ( 
'‘ŒÀ À≈Õƒ— »≈ Œ—“–Œ¬¿', 238, '0', '01-01-1980', '0', 0, 1, NULL); 
INSERT INTO DET_COUNTRY ( COUNTRY_NAME, COUNTRY_CODE_NUM, PRIZN_RS, DT, REC_STATUS, REC_UNLOAD,
REC_PROCESS, ID_FILE ) VALUES ( 
'‘»ÕÀﬂÕƒ»ﬂ', 246, '1', '01-01-1980', '0', 0, 1, NULL); 
INSERT INTO DET_COUNTRY ( COUNTRY_NAME, COUNTRY_CODE_NUM, PRIZN_RS, DT, REC_STATUS, REC_UNLOAD,
REC_PROCESS, ID_FILE ) VALUES ( 
'‘»À»œœ»Õ€', 608, '0', '01-01-1980', '0', 0, 1, NULL); 
INSERT INTO DET_COUNTRY ( COUNTRY_NAME, COUNTRY_CODE_NUM, PRIZN_RS, DT, REC_STATUS, REC_UNLOAD,
REC_PROCESS, ID_FILE ) VALUES ( 
'‘»ƒ∆»', 242, '0', '01-01-1980', '0', 0, 1, NULL); 
INSERT INTO DET_COUNTRY ( COUNTRY_NAME, COUNTRY_CODE_NUM, PRIZN_RS, DT, REC_STATUS, REC_UNLOAD,
REC_PROCESS, ID_FILE ) VALUES ( 
'‘¿–≈–— »≈ Œ—“–Œ¬¿', 234, '0', '01-01-1980', '0', 0, 1, NULL); 
INSERT INTO DET_COUNTRY ( COUNTRY_NAME, COUNTRY_CODE_NUM, PRIZN_RS, DT, REC_STATUS, REC_UNLOAD,
REC_PROCESS, ID_FILE ) VALUES ( 
'Œ—“–Œ¬ ”›… ', 872, '0', '01-01-1980', '0', 0, 1, NULL); 
INSERT INTO DET_COUNTRY ( COUNTRY_NAME, COUNTRY_CODE_NUM, PRIZN_RS, DT, REC_STATUS, REC_UNLOAD,
REC_PROCESS, ID_FILE ) VALUES ( 
'”–”√¬¿…', 858, '0', '01-01-1980', '0', 0, 1, NULL); 
INSERT INTO DET_COUNTRY ( COUNTRY_NAME, COUNTRY_CODE_NUM, PRIZN_RS, DT, REC_STATUS, REC_UNLOAD,
REC_PROCESS, ID_FILE ) VALUES ( 
'”ŒÀÀ»— » ‘”“”Õ¿', 876, '0', '01-01-1980', '0', 0, 1, NULL); 
INSERT INTO DET_COUNTRY ( COUNTRY_NAME, COUNTRY_CODE_NUM, PRIZN_RS, DT, REC_STATUS, REC_UNLOAD,
REC_PROCESS, ID_FILE ) VALUES ( 
'” –¿»Õ¿', 804, '0', '01-01-1980', '0', 0, 1, NULL); 
INSERT INTO DET_COUNTRY ( COUNTRY_NAME, COUNTRY_CODE_NUM, PRIZN_RS, DT, REC_STATUS, REC_UNLOAD,
REC_PROCESS, ID_FILE ) VALUES ( 
'”«¡≈ »—“¿Õ', 860, '0', '01-01-1980', '0', 0, 1, NULL); 
INSERT INTO DET_COUNTRY ( COUNTRY_NAME, COUNTRY_CODE_NUM, PRIZN_RS, DT, REC_STATUS, REC_UNLOAD,
REC_PROCESS, ID_FILE ) VALUES ( 
'”√¿Õƒ¿', 800, '0', '01-01-1980', '0', 0, 1, NULL); 
INSERT INTO DET_COUNTRY ( COUNTRY_NAME, COUNTRY_CODE_NUM, PRIZN_RS, DT, REC_STATUS, REC_UNLOAD,
REC_PROCESS, ID_FILE ) VALUES ( 
'“”–÷»ﬂ', 792, '0', '01-01-1980', '0', 0, 1, NULL); 
INSERT INTO DET_COUNTRY ( COUNTRY_NAME, COUNTRY_CODE_NUM, PRIZN_RS, DT, REC_STATUS, REC_UNLOAD,
REC_PROCESS, ID_FILE ) VALUES ( 
'“”– Ã≈Õ»ﬂ', 795, '0', '01-01-1980', '0', 0, 1, NULL); 
INSERT INTO DET_COUNTRY ( COUNTRY_NAME, COUNTRY_CODE_NUM, PRIZN_RS, DT, REC_STATUS, REC_UNLOAD,
REC_PROCESS, ID_FILE ) VALUES ( 
'“”Õ»—', 788, '0', '01-01-1980', '0', 0, 1, NULL); 
INSERT INTO DET_COUNTRY ( COUNTRY_NAME, COUNTRY_CODE_NUM, PRIZN_RS, DT, REC_STATUS, REC_UNLOAD,
REC_PROCESS, ID_FILE ) VALUES ( 
'“”¬¿À”', 798, '0', '01-01-1980', '0', 0, 1, NULL); 
INSERT INTO DET_COUNTRY ( COUNTRY_NAME, COUNTRY_CODE_NUM, PRIZN_RS, DT, REC_STATUS, REC_UNLOAD,
REC_PROCESS, ID_FILE ) VALUES ( 
'“–»Õ»ƒ¿ƒ » “Œ¡¿√Œ', 780, '0', '01-01-1980', '0', 0, 1, NULL); 
INSERT INTO DET_COUNTRY ( COUNTRY_NAME, COUNTRY_CODE_NUM, PRIZN_RS, DT, REC_STATUS, REC_UNLOAD,
REC_PROCESS, ID_FILE ) VALUES ( 
'“ŒÕ√¿', 776, '0', '01-01-1980', '0', 0, 1, NULL); 
INSERT INTO DET_COUNTRY ( COUNTRY_NAME, COUNTRY_CODE_NUM, PRIZN_RS, DT, REC_STATUS, REC_UNLOAD,
REC_PROCESS, ID_FILE ) VALUES ( 
'“Œ ≈À¿” (ﬁÕ»ŒÕ)', 772, '0', '01-01-1980', '0', 0, 1, NULL); 
INSERT INTO DET_COUNTRY ( COUNTRY_NAME, COUNTRY_CODE_NUM, PRIZN_RS, DT, REC_STATUS, REC_UNLOAD,
REC_PROCESS, ID_FILE ) VALUES ( 
'“Œ√Œ', 768, '0', '01-01-1980', '0', 0, 1, NULL); 
INSERT INTO DET_COUNTRY ( COUNTRY_NAME, COUNTRY_CODE_NUM, PRIZN_RS, DT, REC_STATUS, REC_UNLOAD,
REC_PROCESS, ID_FILE ) VALUES ( 
'œ¿À¿”', 585, '0', '01-01-1980', '0', 0, 1, NULL); 
INSERT INTO DET_COUNTRY ( COUNTRY_NAME, COUNTRY_CODE_NUM, PRIZN_RS, DT, REC_STATUS, REC_UNLOAD,
REC_PROCESS, ID_FILE ) VALUES ( 
'“≈– — »  ¿… Œ—', 796, '0', '01-01-1980', '0', 0, 1, NULL); 
INSERT INTO DET_COUNTRY ( COUNTRY_NAME, COUNTRY_CODE_NUM, PRIZN_RS, DT, REC_STATUS, REC_UNLOAD,
REC_PROCESS, ID_FILE ) VALUES ( 
'“¿Õ«¿Õ»ﬂ', 834, '0', '01-01-1980', '0', 0, 1, NULL); 
INSERT INTO DET_COUNTRY ( COUNTRY_NAME, COUNTRY_CODE_NUM, PRIZN_RS, DT, REC_STATUS, REC_UNLOAD,
REC_PROCESS, ID_FILE ) VALUES ( 
'“¿…¬¿Õ‹', 158, '0', '01-01-1980', '0', 0, 1, NULL); 
INSERT INTO DET_COUNTRY ( COUNTRY_NAME, COUNTRY_CODE_NUM, PRIZN_RS, DT, REC_STATUS, REC_UNLOAD,
REC_PROCESS, ID_FILE ) VALUES ( 
'“¿»À¿Õƒ', 764, '0', '01-01-1980', '0', 0, 1, NULL); 
INSERT INTO DET_COUNTRY ( COUNTRY_NAME, COUNTRY_CODE_NUM, PRIZN_RS, DT, REC_STATUS, REC_UNLOAD,
REC_PROCESS, ID_FILE ) VALUES ( 
'“¿ƒ∆» »—“¿Õ', 762, '0', '01-01-1980', '0', 0, 1, NULL); 
INSERT INTO DET_COUNTRY ( COUNTRY_NAME, COUNTRY_CODE_NUM, PRIZN_RS, DT, REC_STATUS, REC_UNLOAD,
REC_PROCESS, ID_FILE ) VALUES ( 
'—‹≈––¿-À≈ŒÕ≈', 694, '0', '01-01-1980', '0', 0, 1, NULL); 
INSERT INTO DET_COUNTRY ( COUNTRY_NAME, COUNTRY_CODE_NUM, PRIZN_RS, DT, REC_STATUS, REC_UNLOAD,
REC_PROCESS, ID_FILE ) VALUES ( 
'—ÿ¿', 840, '1', '01-01-1980', '0', 0, 1, NULL); 
INSERT INTO DET_COUNTRY ( COUNTRY_NAME, COUNTRY_CODE_NUM, PRIZN_RS, DT, REC_STATUS, REC_UNLOAD,
REC_PROCESS, ID_FILE ) VALUES ( 
'¬»–√»Õ— »≈ Œ—“–Œ¬¿ (—ÿ¿)', 850, '0', '01-01-1980', '0', 0, 1, NULL); 
INSERT INTO DET_COUNTRY ( COUNTRY_NAME, COUNTRY_CODE_NUM, PRIZN_RS, DT, REC_STATUS, REC_UNLOAD,
REC_PROCESS, ID_FILE ) VALUES ( 
'—”–»Õ¿Ã', 740, '0', '01-01-1980', '0', 0, 1, NULL); 
INSERT INTO DET_COUNTRY ( COUNTRY_NAME, COUNTRY_CODE_NUM, PRIZN_RS, DT, REC_STATUS, REC_UNLOAD,
REC_PROCESS, ID_FILE ) VALUES ( 
'—”ƒ¿Õ', 736, '0', '01-01-1980', '0', 0, 1, NULL); 
INSERT INTO DET_COUNTRY ( COUNTRY_NAME, COUNTRY_CODE_NUM, PRIZN_RS, DT, REC_STATUS, REC_UNLOAD,
REC_PROCESS, ID_FILE ) VALUES ( 
'—ŒÃ¿À»', 706, '0', '01-01-1980', '0', 0, 1, NULL); 
INSERT INTO DET_COUNTRY ( COUNTRY_NAME, COUNTRY_CODE_NUM, PRIZN_RS, DT, REC_STATUS, REC_UNLOAD,
REC_PROCESS, ID_FILE ) VALUES ( 
'—ŒÀŒÃŒÕŒ¬€ Œ—“–Œ¬¿', 90, '0', '01-01-1980', '0', 0, 1, NULL); 
INSERT INTO DET_COUNTRY ( COUNTRY_NAME, COUNTRY_CODE_NUM, PRIZN_RS, DT, REC_STATUS, REC_UNLOAD,
REC_PROCESS, ID_FILE ) VALUES ( 
'—»–»ﬂ', 760, '0', '01-01-1980', '0', 0, 1, NULL); 
INSERT INTO DET_COUNTRY ( COUNTRY_NAME, COUNTRY_CODE_NUM, PRIZN_RS, DT, REC_STATUS, REC_UNLOAD,
REC_PROCESS, ID_FILE ) VALUES ( 
'—»Õ√¿œ”–', 702, '0', '01-01-1980', '0', 0, 1, NULL); 
INSERT INTO DET_COUNTRY ( COUNTRY_NAME, COUNTRY_CODE_NUM, PRIZN_RS, DT, REC_STATUS, REC_UNLOAD,
REC_PROCESS, ID_FILE ) VALUES ( 
'—≈Õ“-Àﬁ—»ﬂ', 662, '0', '01-01-1980', '0', 0, 1, NULL); 
INSERT INTO DET_COUNTRY ( COUNTRY_NAME, COUNTRY_CODE_NUM, PRIZN_RS, DT, REC_STATUS, REC_UNLOAD,
REC_PROCESS, ID_FILE ) VALUES ( 
'—≈Õ“- »“— » Õ≈¬»—', 659, '0', '01-01-1980', '0', 0, 1, NULL); 
INSERT INTO DET_COUNTRY ( COUNTRY_NAME, COUNTRY_CODE_NUM, PRIZN_RS, DT, REC_STATUS, REC_UNLOAD,
REC_PROCESS, ID_FILE ) VALUES ( 
'√¿«¿ —≈ “Œ–', 274, '0', '01-01-1980', '0', 0, 1, NULL); 
INSERT INTO DET_COUNTRY ( COUNTRY_NAME, COUNTRY_CODE_NUM, PRIZN_RS, DT, REC_STATUS, REC_UNLOAD,
REC_PROCESS, ID_FILE ) VALUES ( 
'—≈…ÿ≈À‹— »≈ Œ—“–Œ¬¿', 690, '0', '01-01-1980', '0', 0, 1, NULL); 
INSERT INTO DET_COUNTRY ( COUNTRY_NAME, COUNTRY_CODE_NUM, PRIZN_RS, DT, REC_STATUS, REC_UNLOAD,
REC_PROCESS, ID_FILE ) VALUES ( 
'—≈¬≈–Õ€≈ Ã¿–»¿Õ— »≈ Œ—“–Œ¬¿', 580, '0', '01-01-1980', '0', 0, 1, NULL); 
INSERT INTO DET_COUNTRY ( COUNTRY_NAME, COUNTRY_CODE_NUM, PRIZN_RS, DT, REC_STATUS, REC_UNLOAD,
REC_PROCESS, ID_FILE ) VALUES ( 
'—¬¿«»À≈Õƒ', 748, '0', '01-01-1980', '0', 0, 1, NULL); 
INSERT INTO DET_COUNTRY ( COUNTRY_NAME, COUNTRY_CODE_NUM, PRIZN_RS, DT, REC_STATUS, REC_UNLOAD,
REC_PROCESS, ID_FILE ) VALUES ( 
'Œ—“–Œ¬ —¬ﬂ“Œ… ≈À≈Õ€', 654, '0', '01-01-1980', '0', 0, 1, NULL); 
INSERT INTO DET_COUNTRY ( COUNTRY_NAME, COUNTRY_CODE_NUM, PRIZN_RS, DT, REC_STATUS, REC_UNLOAD,
REC_PROCESS, ID_FILE ) VALUES ( 
'—¿”ƒŒ¬— ¿ﬂ ¿–¿¬»ﬂ', 682, '0', '01-01-1980', '0', 0, 1, NULL); 
INSERT INTO DET_COUNTRY ( COUNTRY_NAME, COUNTRY_CODE_NUM, PRIZN_RS, DT, REC_STATUS, REC_UNLOAD,
REC_PROCESS, ID_FILE ) VALUES ( 
'—¿Õ-“ŒÃ≈ » œ–»Õ—»œ»', 678, '0', '01-01-1980', '0', 0, 1, NULL); 
INSERT INTO DET_COUNTRY ( COUNTRY_NAME, COUNTRY_CODE_NUM, PRIZN_RS, DT, REC_STATUS, REC_UNLOAD,
REC_PROCESS, ID_FILE ) VALUES ( 
'—¿Õ-Ã¿–»ÕŒ', 674, '0', '01-01-1980', '0', 0, 1, NULL); 
INSERT INTO DET_COUNTRY ( COUNTRY_NAME, COUNTRY_CODE_NUM, PRIZN_RS, DT, REC_STATUS, REC_UNLOAD,
REC_PROCESS, ID_FILE ) VALUES ( 
'«¿œ¿ƒÕŒ≈ —¿ÃŒ¿', 882, '0', '01-01-1980', '0', 0, 1, NULL); 
INSERT INTO DET_COUNTRY ( COUNTRY_NAME, COUNTRY_CODE_NUM, PRIZN_RS, DT, REC_STATUS, REC_UNLOAD,
REC_PROCESS, ID_FILE ) VALUES ( 
'—¿À‹¬¿ƒŒ–', 222, '0', '01-01-1980', '0', 0, 1, NULL); 
INSERT INTO DET_COUNTRY ( COUNTRY_NAME, COUNTRY_CODE_NUM, PRIZN_RS, DT, REC_STATUS, REC_UNLOAD,
REC_PROCESS, ID_FILE ) VALUES ( 
'—≈Õ“-¬»Õ—≈Õ“ » √–≈Õ¿ƒ»Õ€', 670, '0', '01-01-1980', '0', 0, 1, NULL); 
INSERT INTO DET_COUNTRY ( COUNTRY_NAME, COUNTRY_CODE_NUM, PRIZN_RS, DT, REC_STATUS, REC_UNLOAD,
REC_PROCESS, ID_FILE ) VALUES ( 
'—≈Õ-œ‹≈– » Ã» ≈ÀŒÕ', 666, '0', '01-01-1980', '0', 0, 1, NULL); 
INSERT INTO DET_COUNTRY ( COUNTRY_NAME, COUNTRY_CODE_NUM, PRIZN_RS, DT, REC_STATUS, REC_UNLOAD,
REC_PROCESS, ID_FILE ) VALUES ( 
'–”Ã€Õ»ﬂ', 642, '0', '01-01-1980', '0', 0, 1, NULL); 
INSERT INTO DET_COUNTRY ( COUNTRY_NAME, COUNTRY_CODE_NUM, PRIZN_RS, DT, REC_STATUS, REC_UNLOAD,
REC_PROCESS, ID_FILE ) VALUES ( 
'–”¿Õƒ¿', 646, '0', '01-01-1980', '0', 0, 1, NULL); 
INSERT INTO DET_COUNTRY ( COUNTRY_NAME, COUNTRY_CODE_NUM, PRIZN_RS, DT, REC_STATUS, REC_UNLOAD,
REC_PROCESS, ID_FILE ) VALUES ( 
'Œ—“–Œ¬ –Œ∆ƒ≈—“¬¿', 162, '0', '01-01-1980', '0', 0, 1, NULL); 
INSERT INTO DET_COUNTRY ( COUNTRY_NAME, COUNTRY_CODE_NUM, PRIZN_RS, DT, REC_STATUS, REC_UNLOAD,
REC_PROCESS, ID_FILE ) VALUES ( 
'–≈ﬁÕ‹ŒÕ', 638, '0', '01-01-1980', '0', 0, 1, NULL); 
INSERT INTO DET_COUNTRY ( COUNTRY_NAME, COUNTRY_CODE_NUM, PRIZN_RS, DT, REC_STATUS, REC_UNLOAD,
REC_PROCESS, ID_FILE ) VALUES ( 
'ÃŒÀƒ¿¬»ﬂ', 498, '0', '01-01-1980', '0', 0, 1, NULL); 
INSERT INTO DET_COUNTRY ( COUNTRY_NAME, COUNTRY_CODE_NUM, PRIZN_RS, DT, REC_STATUS, REC_UNLOAD,
REC_PROCESS, ID_FILE ) VALUES ( 
'œ”›–“Œ-–» Œ', 630, '0', '01-01-1980', '0', 0, 1, NULL); 
INSERT INTO DET_COUNTRY ( COUNTRY_NAME, COUNTRY_CODE_NUM, PRIZN_RS, DT, REC_STATUS, REC_UNLOAD,
REC_PROCESS, ID_FILE ) VALUES ( 
'œŒ–“”√¿À»ﬂ', 620, '1', '01-01-1980', '0', 0, 1, NULL); 
INSERT INTO DET_COUNTRY ( COUNTRY_NAME, COUNTRY_CODE_NUM, PRIZN_RS, DT, REC_STATUS, REC_UNLOAD,
REC_PROCESS, ID_FILE ) VALUES ( 
'œŒÀ‹ÿ¿', 616, '0', '01-01-1980', '0', 0, 1, NULL); 
INSERT INTO DET_COUNTRY ( COUNTRY_NAME, COUNTRY_CODE_NUM, PRIZN_RS, DT, REC_STATUS, REC_UNLOAD,
REC_PROCESS, ID_FILE ) VALUES ( 
'œ»“ ›–Õ', 612, '0', '01-01-1980', '0', 0, 1, NULL); 
INSERT INTO DET_COUNTRY ( COUNTRY_NAME, COUNTRY_CODE_NUM, PRIZN_RS, DT, REC_STATUS, REC_UNLOAD,
REC_PROCESS, ID_FILE ) VALUES ( 
'œ≈–”', 604, '0', '01-01-1980', '0', 0, 1, NULL); 
INSERT INTO DET_COUNTRY ( COUNTRY_NAME, COUNTRY_CODE_NUM, PRIZN_RS, DT, REC_STATUS, REC_UNLOAD,
REC_PROCESS, ID_FILE ) VALUES ( 
'œ¿–¿√¬¿…', 600, '0', '01-01-1980', '0', 0, 1, NULL); 
INSERT INTO DET_COUNTRY ( COUNTRY_NAME, COUNTRY_CODE_NUM, PRIZN_RS, DT, REC_STATUS, REC_UNLOAD,
REC_PROCESS, ID_FILE ) VALUES ( 
'œ¿Õ¿Ã¿', 591, '0', '01-01-1980', '0', 0, 1, NULL); 
INSERT INTO DET_COUNTRY ( COUNTRY_NAME, COUNTRY_CODE_NUM, PRIZN_RS, DT, REC_STATUS, REC_UNLOAD,
REC_PROCESS, ID_FILE ) VALUES ( 
'œ¿ »—“¿Õ', 586, '0', '01-01-1980', '0', 0, 1, NULL); 
INSERT INTO DET_COUNTRY ( COUNTRY_NAME, COUNTRY_CODE_NUM, PRIZN_RS, DT, REC_STATUS, REC_UNLOAD,
REC_PROCESS, ID_FILE ) VALUES ( 
'ŒÃ¿Õ', 512, '0', '01-01-1980', '0', 0, 1, NULL); 
INSERT INTO DET_COUNTRY ( COUNTRY_NAME, COUNTRY_CODE_NUM, PRIZN_RS, DT, REC_STATUS, REC_UNLOAD,
REC_PROCESS, ID_FILE ) VALUES ( 
'Œ¡⁄≈ƒ»Õ≈ÕÕ€≈ ¿–¿¡— »≈ ›Ã»–¿“€', 784, '0', '01-01-1980', '0', 0, 1, NULL); 
INSERT INTO DET_COUNTRY ( COUNTRY_NAME, COUNTRY_CODE_NUM, PRIZN_RS, DT, REC_STATUS, REC_UNLOAD,
REC_PROCESS, ID_FILE ) VALUES ( 
'ÕŒ–‘ŒÀ ', 574, '0', '01-01-1980', '0', 0, 1, NULL); 
INSERT INTO DET_COUNTRY ( COUNTRY_NAME, COUNTRY_CODE_NUM, PRIZN_RS, DT, REC_STATUS, REC_UNLOAD,
REC_PROCESS, ID_FILE ) VALUES ( 
'ÕŒ–Ã¿Õƒ— »≈ Œ—“–Œ¬¿', 830, '0', '01-01-1980', '0', 0, 1, NULL); 
INSERT INTO DET_COUNTRY ( COUNTRY_NAME, COUNTRY_CODE_NUM, PRIZN_RS, DT, REC_STATUS, REC_UNLOAD,
REC_PROCESS, ID_FILE ) VALUES ( 
'ÕŒ–¬≈√»ﬂ', 578, '1', '01-01-1980', '0', 0, 1, NULL); 
INSERT INTO DET_COUNTRY ( COUNTRY_NAME, COUNTRY_CODE_NUM, PRIZN_RS, DT, REC_STATUS, REC_UNLOAD,
REC_PROCESS, ID_FILE ) VALUES ( 
'ÕŒ¬¿ﬂ  ¿À≈ƒŒÕ»ﬂ', 540, '0', '01-01-1980', '0', 0, 1, NULL); 
INSERT INTO DET_COUNTRY ( COUNTRY_NAME, COUNTRY_CODE_NUM, PRIZN_RS, DT, REC_STATUS, REC_UNLOAD,
REC_PROCESS, ID_FILE ) VALUES ( 
'ÕŒ¬¿ﬂ «≈À¿Õƒ»ﬂ', 554, '1', '01-01-1980', '0', 0, 1, NULL); 
INSERT INTO DET_COUNTRY ( COUNTRY_NAME, COUNTRY_CODE_NUM, PRIZN_RS, DT, REC_STATUS, REC_UNLOAD,
REC_PROCESS, ID_FILE ) VALUES ( 
'Õ»”›', 570, '0', '01-01-1980', '0', 0, 1, NULL); 
INSERT INTO DET_COUNTRY ( COUNTRY_NAME, COUNTRY_CODE_NUM, PRIZN_RS, DT, REC_STATUS, REC_UNLOAD,
REC_PROCESS, ID_FILE ) VALUES ( 
'Õ» ¿–¿√”¿', 558, '0', '01-01-1980', '0', 0, 1, NULL); 
INSERT INTO DET_COUNTRY ( COUNTRY_NAME, COUNTRY_CODE_NUM, PRIZN_RS, DT, REC_STATUS, REC_UNLOAD,
REC_PROCESS, ID_FILE ) VALUES ( 
'Õ»ƒ≈–À¿Õƒ€', 528, '1', '01-01-1980', '0', 0, 1, NULL); 
INSERT INTO DET_COUNTRY ( COUNTRY_NAME, COUNTRY_CODE_NUM, PRIZN_RS, DT, REC_STATUS, REC_UNLOAD,
REC_PROCESS, ID_FILE ) VALUES ( 
'¿Õ“»À‹— »≈ Œ—“–Œ¬¿ (Õ»ƒ≈–À¿Õƒ€)', 530, '0', '01-01-1980', '0', 0, 1, NULL); 
INSERT INTO DET_COUNTRY ( COUNTRY_NAME, COUNTRY_CODE_NUM, PRIZN_RS, DT, REC_STATUS, REC_UNLOAD,
REC_PROCESS, ID_FILE ) VALUES ( 
'Õ»√≈–»ﬂ', 566, '0', '01-01-1980', '0', 0, 1, NULL); 
INSERT INTO DET_COUNTRY ( COUNTRY_NAME, COUNTRY_CODE_NUM, PRIZN_RS, DT, REC_STATUS, REC_UNLOAD,
REC_PROCESS, ID_FILE ) VALUES ( 
'Õ»√≈–', 562, '0', '01-01-1980', '0', 0, 1, NULL); 
INSERT INTO DET_COUNTRY ( COUNTRY_NAME, COUNTRY_CODE_NUM, PRIZN_RS, DT, REC_STATUS, REC_UNLOAD,
REC_PROCESS, ID_FILE ) VALUES ( 
'Õ≈œ¿À', 524, '0', '01-01-1980', '0', 0, 1, NULL); 
INSERT INTO DET_COUNTRY ( COUNTRY_NAME, COUNTRY_CODE_NUM, PRIZN_RS, DT, REC_STATUS, REC_UNLOAD,
REC_PROCESS, ID_FILE ) VALUES ( 
'Õ¿”–”', 520, '0', '01-01-1980', '0', 0, 1, NULL); 
INSERT INTO DET_COUNTRY ( COUNTRY_NAME, COUNTRY_CODE_NUM, PRIZN_RS, DT, REC_STATUS, REC_UNLOAD,
REC_PROCESS, ID_FILE ) VALUES ( 
'Õ¿Ã»¡»ﬂ', 516, '0', '01-01-1980', '0', 0, 1, NULL); 
INSERT INTO DET_COUNTRY ( COUNTRY_NAME, COUNTRY_CODE_NUM, PRIZN_RS, DT, REC_STATUS, REC_UNLOAD,
REC_PROCESS, ID_FILE ) VALUES ( 
'Ã‹ﬂÕÃ¿', 104, '0', '01-01-1980', '0', 0, 1, NULL); 
INSERT INTO DET_COUNTRY ( COUNTRY_NAME, COUNTRY_CODE_NUM, PRIZN_RS, DT, REC_STATUS, REC_UNLOAD,
REC_PROCESS, ID_FILE ) VALUES ( 
'ÃŒÕ“—≈––¿“', 500, '0', '01-01-1980', '0', 0, 1, NULL); 
INSERT INTO DET_COUNTRY ( COUNTRY_NAME, COUNTRY_CODE_NUM, PRIZN_RS, DT, REC_STATUS, REC_UNLOAD,
REC_PROCESS, ID_FILE ) VALUES ( 
'ÃŒÕ√ŒÀ»ﬂ', 496, '0', '01-01-1980', '0', 0, 1, NULL); 
INSERT INTO DET_COUNTRY ( COUNTRY_NAME, COUNTRY_CODE_NUM, PRIZN_RS, DT, REC_STATUS, REC_UNLOAD,
REC_PROCESS, ID_FILE ) VALUES ( 
'ÃŒÕ¿ Œ', 492, '0', '01-01-1980', '0', 0, 1, NULL); 
INSERT INTO DET_COUNTRY ( COUNTRY_NAME, COUNTRY_CODE_NUM, PRIZN_RS, DT, REC_STATUS, REC_UNLOAD,
REC_PROCESS, ID_FILE ) VALUES ( 
'ÃŒ«¿Ã¡» ', 508, '0', '01-01-1980', '0', 0, 1, NULL); 
INSERT INTO DET_COUNTRY ( COUNTRY_NAME, COUNTRY_CODE_NUM, PRIZN_RS, DT, REC_STATUS, REC_UNLOAD,
REC_PROCESS, ID_FILE ) VALUES ( 
'Ã» –ŒÕ≈«»ﬂ', 583, '0', '01-01-1980', '0', 0, 1, NULL); 
INSERT INTO DET_COUNTRY ( COUNTRY_NAME, COUNTRY_CODE_NUM, PRIZN_RS, DT, REC_STATUS, REC_UNLOAD,
REC_PROCESS, ID_FILE ) VALUES ( 
'Œ—“–Œ¬¿ Ã»ƒ”›…', 488, '0', '01-01-1980', '0', 0, 1, NULL); 
INSERT INTO DET_COUNTRY ( COUNTRY_NAME, COUNTRY_CODE_NUM, PRIZN_RS, DT, REC_STATUS, REC_UNLOAD,
REC_PROCESS, ID_FILE ) VALUES ( 
'Ã≈ —» ¿', 484, '0', '01-01-1980', '0', 0, 1, NULL); 
INSERT INTO DET_COUNTRY ( COUNTRY_NAME, COUNTRY_CODE_NUM, PRIZN_RS, DT, REC_STATUS, REC_UNLOAD,
REC_PROCESS, ID_FILE ) VALUES ( 
'Ã¿–ÿ¿ÀÀŒ¬€ Œ—“–Œ¬¿', 584, '0', '01-01-1980', '0', 0, 1, NULL); 
INSERT INTO DET_COUNTRY ( COUNTRY_NAME, COUNTRY_CODE_NUM, PRIZN_RS, DT, REC_STATUS, REC_UNLOAD,
REC_PROCESS, ID_FILE ) VALUES ( 
'Ã¿–“»Õ» ¿', 474, '0', '01-01-1980', '0', 0, 1, NULL); 
INSERT INTO DET_COUNTRY ( COUNTRY_NAME, COUNTRY_CODE_NUM, PRIZN_RS, DT, REC_STATUS, REC_UNLOAD,
REC_PROCESS, ID_FILE ) VALUES ( 
'Ã¿–Œ  Œ', 504, '0', '01-01-1980', '0', 0, 1, NULL); 
INSERT INTO DET_COUNTRY ( COUNTRY_NAME, COUNTRY_CODE_NUM, PRIZN_RS, DT, REC_STATUS, REC_UNLOAD,
REC_PROCESS, ID_FILE ) VALUES ( 
'Ã¿À‹“¿', 470, '0', '01-01-1980', '0', 0, 1, NULL); 
INSERT INTO DET_COUNTRY ( COUNTRY_NAME, COUNTRY_CODE_NUM, PRIZN_RS, DT, REC_STATUS, REC_UNLOAD,
REC_PROCESS, ID_FILE ) VALUES ( 
'Ã¿À‹ƒ»¬€', 462, '0', '01-01-1980', '0', 0, 1, NULL); 
INSERT INTO DET_COUNTRY ( COUNTRY_NAME, COUNTRY_CODE_NUM, PRIZN_RS, DT, REC_STATUS, REC_UNLOAD,
REC_PROCESS, ID_FILE ) VALUES ( 
'Ã¿À€≈ “»’ŒŒ ≈¿Õ— »≈ Œ—“–Œ¬¿ (—ÿ¿', 581, '0', '01-01-1980', '0', 0, 1, NULL); 
INSERT INTO DET_COUNTRY ( COUNTRY_NAME, COUNTRY_CODE_NUM, PRIZN_RS, DT, REC_STATUS, REC_UNLOAD,
REC_PROCESS, ID_FILE ) VALUES ( 
'Ã¿À»', 466, '0', '01-01-1980', '0', 0, 1, NULL); 
INSERT INTO DET_COUNTRY ( COUNTRY_NAME, COUNTRY_CODE_NUM, PRIZN_RS, DT, REC_STATUS, REC_UNLOAD,
REC_PROCESS, ID_FILE ) VALUES ( 
'Ã¿À¿…«»ﬂ', 458, '0', '01-01-1980', '0', 0, 1, NULL); 
INSERT INTO DET_COUNTRY ( COUNTRY_NAME, COUNTRY_CODE_NUM, PRIZN_RS, DT, REC_STATUS, REC_UNLOAD,
REC_PROCESS, ID_FILE ) VALUES ( 
'¿ŒÃ€Õ‹ (Ã¿ ¿Œ)', 446, '0', '01-01-1980', '0', 0, 1, NULL); 
INSERT INTO DET_COUNTRY ( COUNTRY_NAME, COUNTRY_CODE_NUM, PRIZN_RS, DT, REC_STATUS, REC_UNLOAD,
REC_PROCESS, ID_FILE ) VALUES ( 
'Ã¿ƒ¿√¿— ¿–', 450, '0', '01-01-1980', '0', 0, 1, NULL); 
INSERT INTO DET_COUNTRY ( COUNTRY_NAME, COUNTRY_CODE_NUM, PRIZN_RS, DT, REC_STATUS, REC_UNLOAD,
REC_PROCESS, ID_FILE ) VALUES ( 
'Ã¿¬–»“¿Õ»ﬂ', 478, '0', '01-01-1980', '0', 0, 1, NULL); 
INSERT INTO DET_COUNTRY ( COUNTRY_NAME, COUNTRY_CODE_NUM, PRIZN_RS, DT, REC_STATUS, REC_UNLOAD,
REC_PROCESS, ID_FILE ) VALUES ( 
'Ã¿¬–» »…', 480, '0', '01-01-1980', '0', 0, 1, NULL); 
INSERT INTO DET_COUNTRY ( COUNTRY_NAME, COUNTRY_CODE_NUM, PRIZN_RS, DT, REC_STATUS, REC_UNLOAD,
REC_PROCESS, ID_FILE ) VALUES ( 
'Àﬁ —≈Ã¡”–√', 442, '1', '01-01-1980', '0', 0, 1, NULL); 
INSERT INTO DET_COUNTRY ( COUNTRY_NAME, COUNTRY_CODE_NUM, PRIZN_RS, DT, REC_STATUS, REC_UNLOAD,
REC_PROCESS, ID_FILE ) VALUES ( 
'À»’“≈Õÿ“≈…Õ', 438, '0', '01-01-1980', '0', 0, 1, NULL); 
INSERT INTO DET_COUNTRY ( COUNTRY_NAME, COUNTRY_CODE_NUM, PRIZN_RS, DT, REC_STATUS, REC_UNLOAD,
REC_PROCESS, ID_FILE ) VALUES ( 
'À»“¬¿', 440, '0', '01-01-1980', '0', 0, 1, NULL); 
INSERT INTO DET_COUNTRY ( COUNTRY_NAME, COUNTRY_CODE_NUM, PRIZN_RS, DT, REC_STATUS, REC_UNLOAD,
REC_PROCESS, ID_FILE ) VALUES ( 
'À»¬»ﬂ', 434, '0', '01-01-1980', '0', 0, 1, NULL); 
INSERT INTO DET_COUNTRY ( COUNTRY_NAME, COUNTRY_CODE_NUM, PRIZN_RS, DT, REC_STATUS, REC_UNLOAD,
REC_PROCESS, ID_FILE ) VALUES ( 
'À»¬¿Õ', 422, '0', '01-01-1980', '0', 0, 1, NULL); 
INSERT INTO DET_COUNTRY ( COUNTRY_NAME, COUNTRY_CODE_NUM, PRIZN_RS, DT, REC_STATUS, REC_UNLOAD,
REC_PROCESS, ID_FILE ) VALUES ( 
'À»¡≈–»ﬂ', 430, '0', '01-01-1980', '0', 0, 1, NULL); 
INSERT INTO DET_COUNTRY ( COUNTRY_NAME, COUNTRY_CODE_NUM, PRIZN_RS, DT, REC_STATUS, REC_UNLOAD,
REC_PROCESS, ID_FILE ) VALUES ( 
'À≈—Œ“Œ', 426, '0', '01-01-1980', '0', 0, 1, NULL); 
INSERT INTO DET_COUNTRY ( COUNTRY_NAME, COUNTRY_CODE_NUM, PRIZN_RS, DT, REC_STATUS, REC_UNLOAD,
REC_PROCESS, ID_FILE ) VALUES ( 
'À¿“¬»ﬂ', 428, '0', '01-01-1980', '0', 0, 1, NULL); 
INSERT INTO DET_COUNTRY ( COUNTRY_NAME, COUNTRY_CODE_NUM, PRIZN_RS, DT, REC_STATUS, REC_UNLOAD,
REC_PROCESS, ID_FILE ) VALUES ( 
'À¿Œ—', 418, '0', '01-01-1980', '0', 0, 1, NULL); 
INSERT INTO DET_COUNTRY ( COUNTRY_NAME, COUNTRY_CODE_NUM, PRIZN_RS, DT, REC_STATUS, REC_UNLOAD,
REC_PROCESS, ID_FILE ) VALUES ( 
' €–√€«—“¿Õ', 417, '0', '01-01-1980', '0', 0, 1, NULL); 
INSERT INTO DET_COUNTRY ( COUNTRY_NAME, COUNTRY_CODE_NUM, PRIZN_RS, DT, REC_STATUS, REC_UNLOAD,
REC_PROCESS, ID_FILE ) VALUES ( 
'Œ—“–Œ¬¿  ” ¿', 184, '0', '01-01-1980', '0', 0, 1, NULL); 
INSERT INTO DET_COUNTRY ( COUNTRY_NAME, COUNTRY_CODE_NUM, PRIZN_RS, DT, REC_STATUS, REC_UNLOAD,
REC_PROCESS, ID_FILE ) VALUES ( 
' ”¬≈…“', 414, '0', '01-01-1980', '0', 0, 1, NULL); 
INSERT INTO DET_COUNTRY ( COUNTRY_NAME, COUNTRY_CODE_NUM, PRIZN_RS, DT, REC_STATUS, REC_UNLOAD,
REC_PROCESS, ID_FILE ) VALUES ( 
' ”¡¿', 192, '0', '01-01-1980', '0', 0, 1, NULL); 
INSERT INTO DET_COUNTRY ( COUNTRY_NAME, COUNTRY_CODE_NUM, PRIZN_RS, DT, REC_STATUS, REC_UNLOAD,
REC_PROCESS, ID_FILE ) VALUES ( 
' Œ“-ƒ''»¬”¿–', 384, '0', '01-01-1980', '0', 0, 1, NULL); 
INSERT INTO DET_COUNTRY ( COUNTRY_NAME, COUNTRY_CODE_NUM, PRIZN_RS, DT, REC_STATUS, REC_UNLOAD,
REC_PROCESS, ID_FILE ) VALUES ( 
' Œ—“¿-–» ¿', 188, '0', '01-01-1980', '0', 0, 1, NULL); 
INSERT INTO DET_COUNTRY ( COUNTRY_NAME, COUNTRY_CODE_NUM, PRIZN_RS, DT, REC_STATUS, REC_UNLOAD,
REC_PROCESS, ID_FILE ) VALUES ( 
'–≈—œ”¡À» ¿  Œ–≈ﬂ', 410, '0', '01-01-1980', '0', 0, 1, NULL); 
INSERT INTO DET_COUNTRY ( COUNTRY_NAME, COUNTRY_CODE_NUM, PRIZN_RS, DT, REC_STATUS, REC_UNLOAD,
REC_PROCESS, ID_FILE ) VALUES ( 
' Œ–≈ﬂ ( Õƒ–)', 408, '0', '01-01-1980', '0', 0, 1, NULL); 
INSERT INTO DET_COUNTRY ( COUNTRY_NAME, COUNTRY_CODE_NUM, PRIZN_RS, DT, REC_STATUS, REC_UNLOAD,
REC_PROCESS, ID_FILE ) VALUES ( 
' ŒÕ√Œ', 178, '0', '01-01-1980', '0', 0, 1, NULL); 
INSERT INTO DET_COUNTRY ( COUNTRY_NAME, COUNTRY_CODE_NUM, PRIZN_RS, DT, REC_STATUS, REC_UNLOAD,
REC_PROCESS, ID_FILE ) VALUES ( 
' ŒÀ”Ã¡»ﬂ', 170, '0', '01-01-1980', '0', 0, 1, NULL); 
INSERT INTO DET_COUNTRY ( COUNTRY_NAME, COUNTRY_CODE_NUM, PRIZN_RS, DT, REC_STATUS, REC_UNLOAD,
REC_PROCESS, ID_FILE ) VALUES ( 
' Œ Œ—Œ¬€≈ Œ—“–Œ¬¿', 166, '0', '01-01-1980', '0', 0, 1, NULL); 
INSERT INTO DET_COUNTRY ( COUNTRY_NAME, COUNTRY_CODE_NUM, PRIZN_RS, DT, REC_STATUS, REC_UNLOAD,
REC_PROCESS, ID_FILE ) VALUES ( 
' »“¿…', 156, '0', '01-01-1980', '0', 0, 1, NULL); 
INSERT INTO DET_COUNTRY ( COUNTRY_NAME, COUNTRY_CODE_NUM, PRIZN_RS, DT, REC_STATUS, REC_UNLOAD,
REC_PROCESS, ID_FILE ) VALUES ( 
' »–»¡¿“»', 296, '0', '01-01-1980', '0', 0, 1, NULL); 
INSERT INTO DET_COUNTRY ( COUNTRY_NAME, COUNTRY_CODE_NUM, PRIZN_RS, DT, REC_STATUS, REC_UNLOAD,
REC_PROCESS, ID_FILE ) VALUES ( 
' »œ–', 196, '0', '01-01-1980', '0', 0, 1, NULL); 
INSERT INTO DET_COUNTRY ( COUNTRY_NAME, COUNTRY_CODE_NUM, PRIZN_RS, DT, REC_STATUS, REC_UNLOAD,
REC_PROCESS, ID_FILE ) VALUES ( 
' ≈Õ»ﬂ', 404, '0', '01-01-1980', '0', 0, 1, NULL); 
INSERT INTO DET_COUNTRY ( COUNTRY_NAME, COUNTRY_CODE_NUM, PRIZN_RS, DT, REC_STATUS, REC_UNLOAD,
REC_PROCESS, ID_FILE ) VALUES ( 
' ¿“¿–', 634, '0', '01-01-1980', '0', 0, 1, NULL); 
INSERT INTO DET_COUNTRY ( COUNTRY_NAME, COUNTRY_CODE_NUM, PRIZN_RS, DT, REC_STATUS, REC_UNLOAD,
REC_PROCESS, ID_FILE ) VALUES ( 
' ¿Õ¿ƒ¿', 124, '1', '01-01-1980', '0', 0, 1, NULL); 
INSERT INTO DET_COUNTRY ( COUNTRY_NAME, COUNTRY_CODE_NUM, PRIZN_RS, DT, REC_STATUS, REC_UNLOAD,
REC_PROCESS, ID_FILE ) VALUES ( 
' ¿Ã≈–”Õ', 120, '0', '01-01-1980', '0', 0, 1, NULL); 
INSERT INTO DET_COUNTRY ( COUNTRY_NAME, COUNTRY_CODE_NUM, PRIZN_RS, DT, REC_STATUS, REC_UNLOAD,
REC_PROCESS, ID_FILE ) VALUES ( 
' ¿Ã¡Œƒ∆¿', 116, '0', '01-01-1980', '0', 0, 1, NULL); 
INSERT INTO DET_COUNTRY ( COUNTRY_NAME, COUNTRY_CODE_NUM, PRIZN_RS, DT, REC_STATUS, REC_UNLOAD,
REC_PROCESS, ID_FILE ) VALUES ( 
' ¿…Ã¿Õ', 136, '0', '01-01-1980', '0', 0, 1, NULL); 
INSERT INTO DET_COUNTRY ( COUNTRY_NAME, COUNTRY_CODE_NUM, PRIZN_RS, DT, REC_STATUS, REC_UNLOAD,
REC_PROCESS, ID_FILE ) VALUES ( 
' ¿«¿’—“¿Õ', 398, '0', '01-01-1980', '0', 0, 1, NULL); 
INSERT INTO DET_COUNTRY ( COUNTRY_NAME, COUNTRY_CODE_NUM, PRIZN_RS, DT, REC_STATUS, REC_UNLOAD,
REC_PROCESS, ID_FILE ) VALUES ( 
' ¿¡Œ-¬≈–ƒ≈', 132, '0', '01-01-1980', '0', 0, 1, NULL); 
INSERT INTO DET_COUNTRY ( COUNTRY_NAME, COUNTRY_CODE_NUM, PRIZN_RS, DT, REC_STATUS, REC_UNLOAD,
REC_PROCESS, ID_FILE ) VALUES ( 
'…≈Ã≈Õ', 887, '0', '01-01-1980', '0', 0, 1, NULL); 
INSERT INTO DET_COUNTRY ( COUNTRY_NAME, COUNTRY_CODE_NUM, PRIZN_RS, DT, REC_STATUS, REC_UNLOAD,
REC_PROCESS, ID_FILE ) VALUES ( 
'»“¿À»ﬂ', 380, '1', '01-01-1980', '0', 0, 1, NULL); 
INSERT INTO DET_COUNTRY ( COUNTRY_NAME, COUNTRY_CODE_NUM, PRIZN_RS, DT, REC_STATUS, REC_UNLOAD,
REC_PROCESS, ID_FILE ) VALUES ( 
'»—œ¿Õ»ﬂ', 724, '1', '01-01-1980', '0', 0, 1, NULL); 
INSERT INTO DET_COUNTRY ( COUNTRY_NAME, COUNTRY_CODE_NUM, PRIZN_RS, DT, REC_STATUS, REC_UNLOAD,
REC_PROCESS, ID_FILE ) VALUES ( 
'»—À¿Õƒ»ﬂ', 352, '0', '01-01-1980', '0', 0, 1, NULL); 
INSERT INTO DET_COUNTRY ( COUNTRY_NAME, COUNTRY_CODE_NUM, PRIZN_RS, DT, REC_STATUS, REC_UNLOAD,
REC_PROCESS, ID_FILE ) VALUES ( 
'»–À¿Õƒ»ﬂ', 372, '1', '01-01-1980', '0', 0, 1, NULL); 
INSERT INTO DET_COUNTRY ( COUNTRY_NAME, COUNTRY_CODE_NUM, PRIZN_RS, DT, REC_STATUS, REC_UNLOAD,
REC_PROCESS, ID_FILE ) VALUES ( 
'»–¿Õ', 364, '0', '01-01-1980', '0', 0, 1, NULL); 
INSERT INTO DET_COUNTRY ( COUNTRY_NAME, COUNTRY_CODE_NUM, PRIZN_RS, DT, REC_STATUS, REC_UNLOAD,
REC_PROCESS, ID_FILE ) VALUES ( 
'»–¿ ', 368, '0', '01-01-1980', '0', 0, 1, NULL); 
INSERT INTO DET_COUNTRY ( COUNTRY_NAME, COUNTRY_CODE_NUM, PRIZN_RS, DT, REC_STATUS, REC_UNLOAD,
REC_PROCESS, ID_FILE ) VALUES ( 
'»Œ–ƒ¿Õ»ﬂ', 400, '0', '01-01-1980', '0', 0, 1, NULL); 
INSERT INTO DET_COUNTRY ( COUNTRY_NAME, COUNTRY_CODE_NUM, PRIZN_RS, DT, REC_STATUS, REC_UNLOAD,
REC_PROCESS, ID_FILE ) VALUES ( 
'»ÕƒŒÕ≈«»ﬂ', 360, '0', '01-01-1980', '0', 0, 1, NULL); 
INSERT INTO DET_COUNTRY ( COUNTRY_NAME, COUNTRY_CODE_NUM, PRIZN_RS, DT, REC_STATUS, REC_UNLOAD,
REC_PROCESS, ID_FILE ) VALUES ( 
'»Õƒ»ﬂ', 356, '0', '01-01-1980', '0', 0, 1, NULL); 
INSERT INTO DET_COUNTRY ( COUNTRY_NAME, COUNTRY_CODE_NUM, PRIZN_RS, DT, REC_STATUS, REC_UNLOAD,
REC_PROCESS, ID_FILE ) VALUES ( 
'»«–¿»À‹', 376, '0', '01-01-1980', '0', 0, 1, NULL); 
INSERT INTO DET_COUNTRY ( COUNTRY_NAME, COUNTRY_CODE_NUM, PRIZN_RS, DT, REC_STATUS, REC_UNLOAD,
REC_PROCESS, ID_FILE ) VALUES ( 
'«»Ã¡¿¡¬≈', 716, '0', '01-01-1980', '0', 0, 1, NULL); 
INSERT INTO DET_COUNTRY ( COUNTRY_NAME, COUNTRY_CODE_NUM, PRIZN_RS, DT, REC_STATUS, REC_UNLOAD,
REC_PROCESS, ID_FILE ) VALUES ( 
'«¿œ¿ƒÕ¿ﬂ —¿’¿–¿', 732, '0', '01-01-1980', '0', 0, 1, NULL); 
INSERT INTO DET_COUNTRY ( COUNTRY_NAME, COUNTRY_CODE_NUM, PRIZN_RS, DT, REC_STATUS, REC_UNLOAD,
REC_PROCESS, ID_FILE ) VALUES ( 
'«¿Ã¡»ﬂ', 894, '0', '01-01-1980', '0', 0, 1, NULL); 
INSERT INTO DET_COUNTRY ( COUNTRY_NAME, COUNTRY_CODE_NUM, PRIZN_RS, DT, REC_STATUS, REC_UNLOAD,
REC_PROCESS, ID_FILE ) VALUES ( 
'«¿»–', 180, '0', '01-01-1980', '0', 0, 1, NULL); 
INSERT INTO DET_COUNTRY ( COUNTRY_NAME, COUNTRY_CODE_NUM, PRIZN_RS, DT, REC_STATUS, REC_UNLOAD,
REC_PROCESS, ID_FILE ) VALUES ( 
'≈√»œ≈“', 818, '0', '01-01-1980', '0', 0, 1, NULL); 
INSERT INTO DET_COUNTRY ( COUNTRY_NAME, COUNTRY_CODE_NUM, PRIZN_RS, DT, REC_STATUS, REC_UNLOAD,
REC_PROCESS, ID_FILE ) VALUES ( 
'ƒŒÃ»Õ» ¿Õ— ¿ﬂ –≈—œ”¡À» ¿', 214, '0', '01-01-1980', '0', 0, 1, NULL); 
INSERT INTO DET_COUNTRY ( COUNTRY_NAME, COUNTRY_CODE_NUM, PRIZN_RS, DT, REC_STATUS, REC_UNLOAD,
REC_PROCESS, ID_FILE ) VALUES ( 
'ƒŒÃ»Õ» ¿', 212, '0', '01-01-1980', '0', 0, 1, NULL); 
INSERT INTO DET_COUNTRY ( COUNTRY_NAME, COUNTRY_CODE_NUM, PRIZN_RS, DT, REC_STATUS, REC_UNLOAD,
REC_PROCESS, ID_FILE ) VALUES ( 
'ƒ∆ŒÕ—“ŒÕ ¿“ŒÀÀ', 396, '0', '01-01-1980', '0', 0, 1, NULL); 
INSERT INTO DET_COUNTRY ( COUNTRY_NAME, COUNTRY_CODE_NUM, PRIZN_RS, DT, REC_STATUS, REC_UNLOAD,
REC_PROCESS, ID_FILE ) VALUES ( 
'ƒ∆»¡”“»', 262, '0', '01-01-1980', '0', 0, 1, NULL); 
INSERT INTO DET_COUNTRY ( COUNTRY_NAME, COUNTRY_CODE_NUM, PRIZN_RS, DT, REC_STATUS, REC_UNLOAD,
REC_PROCESS, ID_FILE ) VALUES ( 
'√”¿Ã', 316, '0', '01-01-1980', '0', 0, 1, NULL); 
INSERT INTO DET_COUNTRY ( COUNTRY_NAME, COUNTRY_CODE_NUM, PRIZN_RS, DT, REC_STATUS, REC_UNLOAD,
REC_PROCESS, ID_FILE ) VALUES ( 
'√–”«»ﬂ', 268, '0', '01-01-1980', '0', 0, 1, NULL); 
INSERT INTO DET_COUNTRY ( COUNTRY_NAME, COUNTRY_CODE_NUM, PRIZN_RS, DT, REC_STATUS, REC_UNLOAD,
REC_PROCESS, ID_FILE ) VALUES ( 
'√–≈÷»ﬂ', 300, '1', '01-01-1980', '0', 0, 1, NULL); 
INSERT INTO DET_COUNTRY ( COUNTRY_NAME, COUNTRY_CODE_NUM, PRIZN_RS, DT, REC_STATUS, REC_UNLOAD,
REC_PROCESS, ID_FILE ) VALUES ( 
'√–≈ÕÀ¿Õƒ»ﬂ', 304, '0', '01-01-1980', '0', 0, 1, NULL); 
INSERT INTO DET_COUNTRY ( COUNTRY_NAME, COUNTRY_CODE_NUM, PRIZN_RS, DT, REC_STATUS, REC_UNLOAD,
REC_PROCESS, ID_FILE ) VALUES ( 
'√–≈Õ¿ƒ¿', 308, '0', '01-01-1980', '0', 0, 1, NULL); 
INSERT INTO DET_COUNTRY ( COUNTRY_NAME, COUNTRY_CODE_NUM, PRIZN_RS, DT, REC_STATUS, REC_UNLOAD,
REC_PROCESS, ID_FILE ) VALUES ( 
'—ﬂÕ√¿Õ (√ŒÕ ŒÕ√)', 344, '0', '01-01-1980', '0', 0, 1, NULL); 
INSERT INTO DET_COUNTRY ( COUNTRY_NAME, COUNTRY_CODE_NUM, PRIZN_RS, DT, REC_STATUS, REC_UNLOAD,
REC_PROCESS, ID_FILE ) VALUES ( 
'√ŒÕƒ”–¿—', 340, '0', '01-01-1980', '0', 0, 1, NULL); 
INSERT INTO DET_COUNTRY ( COUNTRY_NAME, COUNTRY_CODE_NUM, PRIZN_RS, DT, REC_STATUS, REC_UNLOAD,
REC_PROCESS, ID_FILE ) VALUES ( 
'√»¡–¿À“¿–', 292, '0', '01-01-1980', '0', 0, 1, NULL); 
INSERT INTO DET_COUNTRY ( COUNTRY_NAME, COUNTRY_CODE_NUM, PRIZN_RS, DT, REC_STATUS, REC_UNLOAD,
REC_PROCESS, ID_FILE ) VALUES ( 
'√≈–Ã¿Õ»ﬂ', 276, '1', '01-01-1980', '0', 0, 1, NULL); 
INSERT INTO DET_COUNTRY ( COUNTRY_NAME, COUNTRY_CODE_NUM, PRIZN_RS, DT, REC_STATUS, REC_UNLOAD,
REC_PROCESS, ID_FILE ) VALUES ( 
'√¬»Õ≈ﬂ-¡»—¿”', 624, '0', '01-01-1980', '0', 0, 1, NULL); 
INSERT INTO DET_COUNTRY ( COUNTRY_NAME, COUNTRY_CODE_NUM, PRIZN_RS, DT, REC_STATUS, REC_UNLOAD,
REC_PROCESS, ID_FILE ) VALUES ( 
'√¬»Õ≈ﬂ', 324, '0', '01-01-1980', '0', 0, 1, NULL); 
INSERT INTO DET_COUNTRY ( COUNTRY_NAME, COUNTRY_CODE_NUM, PRIZN_RS, DT, REC_STATUS, REC_UNLOAD,
REC_PROCESS, ID_FILE ) VALUES ( 
'√¿Õ¿', 288, '0', '01-01-1980', '0', 0, 1, NULL); 
INSERT INTO DET_COUNTRY ( COUNTRY_NAME, COUNTRY_CODE_NUM, PRIZN_RS, DT, REC_STATUS, REC_UNLOAD,
REC_PROCESS, ID_FILE ) VALUES ( 
'¬‹≈“Õ¿Ã', 704, '0', '01-01-1980', '0', 0, 1, NULL); 
INSERT INTO DET_COUNTRY ( COUNTRY_NAME, COUNTRY_CODE_NUM, PRIZN_RS, DT, REC_STATUS, REC_UNLOAD,
REC_PROCESS, ID_FILE ) VALUES ( 
'¬≈Õ√–»ﬂ', 348, '0', '01-01-1980', '0', 0, 1, NULL); 
INSERT INTO DET_COUNTRY ( COUNTRY_NAME, COUNTRY_CODE_NUM, PRIZN_RS, DT, REC_STATUS, REC_UNLOAD,
REC_PROCESS, ID_FILE ) VALUES ( 
'¬¿“» ¿Õ', 336, '0', '01-01-1980', '0', 0, 1, NULL); 
INSERT INTO DET_COUNTRY ( COUNTRY_NAME, COUNTRY_CODE_NUM, PRIZN_RS, DT, REC_STATUS, REC_UNLOAD,
REC_PROCESS, ID_FILE ) VALUES ( 
'¡”– »Õ¿-‘¿—Œ', 854, '0', '01-01-1980', '0', 0, 1, NULL); 
INSERT INTO DET_COUNTRY ( COUNTRY_NAME, COUNTRY_CODE_NUM, PRIZN_RS, DT, REC_STATUS, REC_UNLOAD,
REC_PROCESS, ID_FILE ) VALUES ( 
'¡–¿«»À»ﬂ', 76, '0', '01-01-1980', '0', 0, 1, NULL); 
INSERT INTO DET_COUNTRY ( COUNTRY_NAME, COUNTRY_CODE_NUM, PRIZN_RS, DT, REC_STATUS, REC_UNLOAD,
REC_PROCESS, ID_FILE ) VALUES ( 
'¡Œ“—¬¿Õ¿', 72, '0', '01-01-1980', '0', 0, 1, NULL); 
INSERT INTO DET_COUNTRY ( COUNTRY_NAME, COUNTRY_CODE_NUM, PRIZN_RS, DT, REC_STATUS, REC_UNLOAD,
REC_PROCESS, ID_FILE ) VALUES ( 
'¡ŒÀ»¬»ﬂ', 68, '0', '01-01-1980', '0', 0, 1, NULL); 
INSERT INTO DET_COUNTRY ( COUNTRY_NAME, COUNTRY_CODE_NUM, PRIZN_RS, DT, REC_STATUS, REC_UNLOAD,
REC_PROCESS, ID_FILE ) VALUES ( 
'¡≈Õ»Õ', 204, '0', '01-01-1980', '0', 0, 1, NULL); 
INSERT INTO DET_COUNTRY ( COUNTRY_NAME, COUNTRY_CODE_NUM, PRIZN_RS, DT, REC_STATUS, REC_UNLOAD,
REC_PROCESS, ID_FILE ) VALUES ( 
'¡≈ÀŒ–”——»ﬂ', 112, '0', '01-01-1980', '0', 0, 1, NULL); 
INSERT INTO DET_COUNTRY ( COUNTRY_NAME, COUNTRY_CODE_NUM, PRIZN_RS, DT, REC_STATUS, REC_UNLOAD,
REC_PROCESS, ID_FILE ) VALUES ( 
'¿–Ã≈Õ»ﬂ', 51, '0', '01-01-1980', '0', 0, 1, NULL); 
INSERT INTO DET_COUNTRY ( COUNTRY_NAME, COUNTRY_CODE_NUM, PRIZN_RS, DT, REC_STATUS, REC_UNLOAD,
REC_PROCESS, ID_FILE ) VALUES ( 
'¿Õ“¿– “»ƒ¿', 10, '0', '01-01-1980', '0', 0, 1, NULL); 
INSERT INTO DET_COUNTRY ( COUNTRY_NAME, COUNTRY_CODE_NUM, PRIZN_RS, DT, REC_STATUS, REC_UNLOAD,
REC_PROCESS, ID_FILE ) VALUES ( 
'¬Œ—“Œ◊ÕŒ≈ —¿ÃŒ¿ (—ÿ¿)', 16, '0', '01-01-1980', '0', 0, 1, NULL); 
INSERT INTO DET_COUNTRY ( COUNTRY_NAME, COUNTRY_CODE_NUM, PRIZN_RS, DT, REC_STATUS, REC_UNLOAD,
REC_PROCESS, ID_FILE ) VALUES ( 
'¿¬—“–»ﬂ', 40, '1', '01-01-1980', '0', 0, 1, NULL); 
INSERT INTO DET_COUNTRY ( COUNTRY_NAME, COUNTRY_CODE_NUM, PRIZN_RS, DT, REC_STATUS, REC_UNLOAD,
REC_PROCESS, ID_FILE ) VALUES ( 
'√¬¿“≈Ã¿À¿', 320, '0', '01-01-1980', '0', 0, 1, NULL); 
INSERT INTO DET_COUNTRY ( COUNTRY_NAME, COUNTRY_CODE_NUM, PRIZN_RS, DT, REC_STATUS, REC_UNLOAD,
REC_PROCESS, ID_FILE ) VALUES ( 
'√¬¿ƒ≈À”œ¿', 312, '0', '01-01-1980', '0', 0, 1, NULL); 
INSERT INTO DET_COUNTRY ( COUNTRY_NAME, COUNTRY_CODE_NUM, PRIZN_RS, DT, REC_STATUS, REC_UNLOAD,
REC_PROCESS, ID_FILE ) VALUES ( 
'√¿Ã¡»ﬂ', 270, '0', '01-01-1980', '0', 0, 1, NULL); 
INSERT INTO DET_COUNTRY ( COUNTRY_NAME, COUNTRY_CODE_NUM, PRIZN_RS, DT, REC_STATUS, REC_UNLOAD,
REC_PROCESS, ID_FILE ) VALUES ( 
'√¿…¿Õ¿', 328, '0', '01-01-1980', '0', 0, 1, NULL); 
INSERT INTO DET_COUNTRY ( COUNTRY_NAME, COUNTRY_CODE_NUM, PRIZN_RS, DT, REC_STATUS, REC_UNLOAD,
REC_PROCESS, ID_FILE ) VALUES ( 
'√¿»“»', 332, '0', '01-01-1980', '0', 0, 1, NULL); 
INSERT INTO DET_COUNTRY ( COUNTRY_NAME, COUNTRY_CODE_NUM, PRIZN_RS, DT, REC_STATUS, REC_UNLOAD,
REC_PROCESS, ID_FILE ) VALUES ( 
'√¿¡ŒÕ', 266, '0', '01-01-1980', '0', 0, 1, NULL); 
INSERT INTO DET_COUNTRY ( COUNTRY_NAME, COUNTRY_CODE_NUM, PRIZN_RS, DT, REC_STATUS, REC_UNLOAD,
REC_PROCESS, ID_FILE ) VALUES ( 
'¬Œ—“Œ◊Õ€… “»ÃŒ–', 626, '0', '01-01-1980', '0', 0, 1, NULL); 
INSERT INTO DET_COUNTRY ( COUNTRY_NAME, COUNTRY_CODE_NUM, PRIZN_RS, DT, REC_STATUS, REC_UNLOAD,
REC_PROCESS, ID_FILE ) VALUES ( 
'¬≈Õ≈—”›À¿', 862, '0', '01-01-1980', '0', 0, 1, NULL); 
INSERT INTO DET_COUNTRY ( COUNTRY_NAME, COUNTRY_CODE_NUM, PRIZN_RS, DT, REC_STATUS, REC_UNLOAD,
REC_PROCESS, ID_FILE ) VALUES ( 
'¬≈À» Œ¡–»“¿Õ»ﬂ', 826, '1', '01-01-1980', '0', 0, 1, NULL); 
INSERT INTO DET_COUNTRY ( COUNTRY_NAME, COUNTRY_CODE_NUM, PRIZN_RS, DT, REC_STATUS, REC_UNLOAD,
REC_PROCESS, ID_FILE ) VALUES ( 
'¬¿Õ”¿“”', 548, '0', '01-01-1980', '0', 0, 1, NULL); 
INSERT INTO DET_COUNTRY ( COUNTRY_NAME, COUNTRY_CODE_NUM, PRIZN_RS, DT, REC_STATUS, REC_UNLOAD,
REC_PROCESS, ID_FILE ) VALUES ( 
'¡”“¿Õ', 64, '0', '01-01-1980', '0', 0, 1, NULL); 
INSERT INTO DET_COUNTRY ( COUNTRY_NAME, COUNTRY_CODE_NUM, PRIZN_RS, DT, REC_STATUS, REC_UNLOAD,
REC_PROCESS, ID_FILE ) VALUES ( 
'¡”–”Õƒ»', 108, '0', '01-01-1980', '0', 0, 1, NULL); 
INSERT INTO DET_COUNTRY ( COUNTRY_NAME, COUNTRY_CODE_NUM, PRIZN_RS, DT, REC_STATUS, REC_UNLOAD,
REC_PROCESS, ID_FILE ) VALUES ( 
'¡”¬≈', 74, '0', '01-01-1980', '0', 0, 1, NULL); 
INSERT INTO DET_COUNTRY ( COUNTRY_NAME, COUNTRY_CODE_NUM, PRIZN_RS, DT, REC_STATUS, REC_UNLOAD,
REC_PROCESS, ID_FILE ) VALUES ( 
'¡–”Õ≈…', 96, '0', '01-01-1980', '0', 0, 1, NULL); 
INSERT INTO DET_COUNTRY ( COUNTRY_NAME, COUNTRY_CODE_NUM, PRIZN_RS, DT, REC_STATUS, REC_UNLOAD,
REC_PROCESS, ID_FILE ) VALUES ( 
'¬»–√»Õ— »≈ Œ—“–Œ¬¿ (¡–»“.)', 92, '0', '01-01-1980', '0', 0, 1, NULL); 
INSERT INTO DET_COUNTRY ( COUNTRY_NAME, COUNTRY_CODE_NUM, PRIZN_RS, DT, REC_STATUS, REC_UNLOAD,
REC_PROCESS, ID_FILE ) VALUES ( 
'¡–»“¿Õ— ¿ﬂ “≈––»“Œ–»ﬂ ¬ »Õƒ.Œ ≈¿', 86, '0', '01-01-1980', '0', 0, 1, NULL); 
INSERT INTO DET_COUNTRY ( COUNTRY_NAME, COUNTRY_CODE_NUM, PRIZN_RS, DT, REC_STATUS, REC_UNLOAD,
REC_PROCESS, ID_FILE ) VALUES ( 
'¡ŒÀ√¿–»ﬂ', 100, '0', '01-01-1980', '0', 0, 1, NULL); 
INSERT INTO DET_COUNTRY ( COUNTRY_NAME, COUNTRY_CODE_NUM, PRIZN_RS, DT, REC_STATUS, REC_UNLOAD,
REC_PROCESS, ID_FILE ) VALUES ( 
'¡≈–Ã”ƒ— »≈ Œ—“–Œ¬¿', 60, '0', '01-01-1980', '0', 0, 1, NULL); 
INSERT INTO DET_COUNTRY ( COUNTRY_NAME, COUNTRY_CODE_NUM, PRIZN_RS, DT, REC_STATUS, REC_UNLOAD,
REC_PROCESS, ID_FILE ) VALUES ( 
'¡≈À‹√»ﬂ', 56, '1', '01-01-1980', '0', 0, 1, NULL); 
INSERT INTO DET_COUNTRY ( COUNTRY_NAME, COUNTRY_CODE_NUM, PRIZN_RS, DT, REC_STATUS, REC_UNLOAD,
REC_PROCESS, ID_FILE ) VALUES ( 
'¡≈À»«', 84, '0', '01-01-1980', '0', 0, 1, NULL); 
INSERT INTO DET_COUNTRY ( COUNTRY_NAME, COUNTRY_CODE_NUM, PRIZN_RS, DT, REC_STATUS, REC_UNLOAD,
REC_PROCESS, ID_FILE ) VALUES ( 
'¡¿’–≈…Õ', 48, '0', '01-01-1980', '0', 0, 1, NULL); 
INSERT INTO DET_COUNTRY ( COUNTRY_NAME, COUNTRY_CODE_NUM, PRIZN_RS, DT, REC_STATUS, REC_UNLOAD,
REC_PROCESS, ID_FILE ) VALUES ( 
'¡¿–¡¿ƒŒ—', 52, '0', '01-01-1980', '0', 0, 1, NULL); 
INSERT INTO DET_COUNTRY ( COUNTRY_NAME, COUNTRY_CODE_NUM, PRIZN_RS, DT, REC_STATUS, REC_UNLOAD,
REC_PROCESS, ID_FILE ) VALUES ( 
'¡¿Õ√À¿ƒ≈ÿ', 50, '0', '01-01-1980', '0', 0, 1, NULL); 
INSERT INTO DET_COUNTRY ( COUNTRY_NAME, COUNTRY_CODE_NUM, PRIZN_RS, DT, REC_STATUS, REC_UNLOAD,
REC_PROCESS, ID_FILE ) VALUES ( 
'¿‘√¿Õ»—“¿Õ', 4, '0', '01-01-1980', '0', 0, 1, NULL); 
INSERT INTO DET_COUNTRY ( COUNTRY_NAME, COUNTRY_CODE_NUM, PRIZN_RS, DT, REC_STATUS, REC_UNLOAD,
REC_PROCESS, ID_FILE ) VALUES ( 
'¿–”¡¿', 533, '0', '01-01-1980', '0', 0, 1, NULL); 
INSERT INTO DET_COUNTRY ( COUNTRY_NAME, COUNTRY_CODE_NUM, PRIZN_RS, DT, REC_STATUS, REC_UNLOAD,
REC_PROCESS, ID_FILE ) VALUES ( 
'¿–√≈Õ“»Õ¿', 32, '0', '01-01-1980', '0', 0, 1, NULL); 
INSERT INTO DET_COUNTRY ( COUNTRY_NAME, COUNTRY_CODE_NUM, PRIZN_RS, DT, REC_STATUS, REC_UNLOAD,
REC_PROCESS, ID_FILE ) VALUES ( 
'¿Õ“»√”¿ » ¡¿–¡”ƒ¿', 28, '0', '01-01-1980', '0', 0, 1, NULL); 
INSERT INTO DET_COUNTRY ( COUNTRY_NAME, COUNTRY_CODE_NUM, PRIZN_RS, DT, REC_STATUS, REC_UNLOAD,
REC_PROCESS, ID_FILE ) VALUES ( 
'¿ÕƒŒ––¿', 20, '0', '01-01-1980', '0', 0, 1, NULL); 
INSERT INTO DET_COUNTRY ( COUNTRY_NAME, COUNTRY_CODE_NUM, PRIZN_RS, DT, REC_STATUS, REC_UNLOAD,
REC_PROCESS, ID_FILE ) VALUES ( 
'¿Õ√ŒÀ¿', 24, '0', '01-01-1980', '0', 0, 1, NULL); 
INSERT INTO DET_COUNTRY ( COUNTRY_NAME, COUNTRY_CODE_NUM, PRIZN_RS, DT, REC_STATUS, REC_UNLOAD,
REC_PROCESS, ID_FILE ) VALUES ( 
'¿Õ√»À‹ﬂ', 660, '0', '01-01-1980', '0', 0, 1, NULL); 
INSERT INTO DET_COUNTRY ( COUNTRY_NAME, COUNTRY_CODE_NUM, PRIZN_RS, DT, REC_STATUS, REC_UNLOAD,
REC_PROCESS, ID_FILE ) VALUES ( 
'¿À∆»–', 12, '0', '01-01-1980', '0', 0, 1, NULL); 
INSERT INTO DET_COUNTRY ( COUNTRY_NAME, COUNTRY_CODE_NUM, PRIZN_RS, DT, REC_STATUS, REC_UNLOAD,
REC_PROCESS, ID_FILE ) VALUES ( 
'¿À¡¿Õ»ﬂ', 8, '0', '01-01-1980', '0', 0, 1, NULL); 
INSERT INTO DET_COUNTRY ( COUNTRY_NAME, COUNTRY_CODE_NUM, PRIZN_RS, DT, REC_STATUS, REC_UNLOAD,
REC_PROCESS, ID_FILE ) VALUES ( 
'¿«≈–¡¿…ƒ∆¿Õ', 31, '0', '01-01-1980', '0', 0, 1, NULL); 
INSERT INTO DET_COUNTRY ( COUNTRY_NAME, COUNTRY_CODE_NUM, PRIZN_RS, DT, REC_STATUS, REC_UNLOAD,
REC_PROCESS, ID_FILE ) VALUES ( 
'¿¬—“–¿À»ﬂ', 36, '1', '01-01-1980', '0', 0, 1, NULL); 
INSERT INTO DET_COUNTRY ( COUNTRY_NAME, COUNTRY_CODE_NUM, PRIZN_RS, DT, REC_STATUS, REC_UNLOAD,
REC_PROCESS, ID_FILE ) VALUES ( 
'–Œ——»ﬂ', 643, '0', '01-01-1980', '0', 0, 1, NULL); 
INSERT INTO DET_COUNTRY ( COUNTRY_NAME, COUNTRY_CODE_NUM, PRIZN_RS, DT, REC_STATUS, REC_UNLOAD,
REC_PROCESS, ID_FILE ) VALUES ( 
'Õ≈ Œœ–≈ƒ≈À≈ÕŒ', -1, '0', '01-01-1980', '0', 0, 1, NULL); 
INSERT INTO DET_COUNTRY ( COUNTRY_NAME, COUNTRY_CODE_NUM, PRIZN_RS, DT, REC_STATUS, REC_UNLOAD,
REC_PROCESS, ID_FILE ) VALUES ( 
'‘–¿Õ÷”«— ¿ﬂ œŒÀ»Õ≈«»ﬂ', 258, '0', '01-01-1980', '0', 0, 1, NULL); 
INSERT INTO DET_COUNTRY ( COUNTRY_NAME, COUNTRY_CODE_NUM, PRIZN_RS, DT, REC_STATUS, REC_UNLOAD,
REC_PROCESS, ID_FILE ) VALUES ( 
'—≈Õ≈√¿À', 686, '0', '01-01-1980', '0', 0, 1, NULL); 
INSERT INTO DET_COUNTRY ( COUNTRY_NAME, COUNTRY_CODE_NUM, PRIZN_RS, DT, REC_STATUS, REC_UNLOAD,
REC_PROCESS, ID_FILE ) VALUES ( 
'œ¿œ”¿-ÕŒ¬¿ﬂ √¬»Õ≈ﬂ', 598, '0', '01-01-1980', '0', 0, 1, NULL); 
INSERT INTO DET_COUNTRY ( COUNTRY_NAME, COUNTRY_CODE_NUM, PRIZN_RS, DT, REC_STATUS, REC_UNLOAD,
REC_PROCESS, ID_FILE ) VALUES ( 
'Ã¿À¿¬»', 454, '0', '01-01-1980', '0', 0, 1, NULL); 
INSERT INTO DET_COUNTRY ( COUNTRY_NAME, COUNTRY_CODE_NUM, PRIZN_RS, DT, REC_STATUS, REC_UNLOAD,
REC_PROCESS, ID_FILE ) VALUES ( 
' ŒÃŒ–— »≈ Œ—“–Œ¬¿', 174, '0', '01-01-1980', '0', 0, 1, NULL); 
INSERT INTO DET_COUNTRY ( COUNTRY_NAME, COUNTRY_CODE_NUM, PRIZN_RS, DT, REC_STATUS, REC_UNLOAD,
REC_PROCESS, ID_FILE ) VALUES ( 
'ƒ¿Õ»ﬂ', 208, '1', '01-01-1980', '0', 0, 1, NULL); 
INSERT INTO DET_COUNTRY ( COUNTRY_NAME, COUNTRY_CODE_NUM, PRIZN_RS, DT, REC_STATUS, REC_UNLOAD,
REC_PROCESS, ID_FILE ) VALUES ( 
'¡¿√¿Ã— »≈ Œ—“–Œ¬¿', 44, '0', '01-01-1980', '0', 0, 1, NULL); 
COMMIT;
