INSERT INTO DET_PLAN_BAL ( PLAN_BAL_CODE, PLAN_BAL_NAME, DT, REC_STATUS, REC_UNLOAD, REC_PROCESS,
ID_FILE ) VALUES ( 
'BANK_RUR', 'Рабочий план счетов', '01-01-1980', '0', NULL, NULL, NULL); 
COMMIT;
