INSERT INTO DET_FINSTR ( FINSTR_CODE, FINSTR_NAME, FINSTR_NAME_S, DT, REC_STATUS,
SYSMOMENT ) VALUES ( 
'280', 'Немецкая марка до 2001 г.', 'Немецкая марка до 2001 г.', '01-01-1980', '0'
,  TO_Date( '12/22/2004 01:13:33 PM', 'MM/DD/YYYY HH:MI:SS AM')); 
INSERT INTO DET_FINSTR ( FINSTR_CODE, FINSTR_NAME, FINSTR_NAME_S, DT, REC_STATUS,
SYSMOMENT ) VALUES ( 
'R*R', 'Суммарный эквивалент инвалют', 'Суммарный эквивалент инвалют', '01-01-1980'
, '0',  TO_Date( '12/22/2004 01:13:33 PM', 'MM/DD/YYYY HH:MI:SS AM')); 
INSERT INTO DET_FINSTR ( FINSTR_CODE, FINSTR_NAME, FINSTR_NAME_S, DT, REC_STATUS,
SYSMOMENT ) VALUES ( 
'EU*', 'Группа EUR', 'Группа EUR', '01-01-1980', '0',  TO_Date( '12/22/2004 01:13:33 PM', 'MM/DD/YYYY HH:MI:SS AM')); 
INSERT INTO DET_FINSTR ( FINSTR_CODE, FINSTR_NAME, FINSTR_NAME_S, DT, REC_STATUS,
SYSMOMENT ) VALUES ( 
'AFA', 'Афгани', 'Афгани', '01-01-1980', '0',  TO_Date( '12/22/2004 01:13:33 PM', 'MM/DD/YYYY HH:MI:SS AM')); 
INSERT INTO DET_FINSTR ( FINSTR_CODE, FINSTR_NAME, FINSTR_NAME_S, DT, REC_STATUS,
SYSMOMENT ) VALUES ( 
'DZD', 'Алжирский динар', 'Алжирский динар', '01-01-1980', '0',  TO_Date( '12/22/2004 01:13:33 PM', 'MM/DD/YYYY HH:MI:SS AM')); 
INSERT INTO DET_FINSTR ( FINSTR_CODE, FINSTR_NAME, FINSTR_NAME_S, DT, REC_STATUS,
SYSMOMENT ) VALUES ( 
'USD', 'Доллар США', 'Доллар США', '01-01-1980', '0',  TO_Date( '12/22/2004 01:13:33 PM', 'MM/DD/YYYY HH:MI:SS AM')); 
INSERT INTO DET_FINSTR ( FINSTR_CODE, FINSTR_NAME, FINSTR_NAME_S, DT, REC_STATUS,
SYSMOMENT ) VALUES ( 
'ESP', 'Испанская песета', 'Испанская песета', '01-01-1980', '0',  TO_Date( '12/22/2004 01:13:33 PM', 'MM/DD/YYYY HH:MI:SS AM')); 
INSERT INTO DET_FINSTR ( FINSTR_CODE, FINSTR_NAME, FINSTR_NAME_S, DT, REC_STATUS,
SYSMOMENT ) VALUES ( 
'FRF', 'Французский франк', 'Французский франк', '01-01-1980', '0',  TO_Date( '12/22/2004 01:13:33 PM', 'MM/DD/YYYY HH:MI:SS AM')); 
INSERT INTO DET_FINSTR ( FINSTR_CODE, FINSTR_NAME, FINSTR_NAME_S, DT, REC_STATUS,
SYSMOMENT ) VALUES ( 
'AUD', 'Австралийский доллар', 'Австралийский доллар', '01-01-1980', '0',  TO_Date( '12/22/2004 01:13:33 PM', 'MM/DD/YYYY HH:MI:SS AM')); 
INSERT INTO DET_FINSTR ( FINSTR_CODE, FINSTR_NAME, FINSTR_NAME_S, DT, REC_STATUS,
SYSMOMENT ) VALUES ( 
'ATS', 'Австрийский Шиллинг', 'Австрийский Шиллинг', '01-01-1980', '0',  TO_Date( '12/22/2004 01:13:33 PM', 'MM/DD/YYYY HH:MI:SS AM')); 
INSERT INTO DET_FINSTR ( FINSTR_CODE, FINSTR_NAME, FINSTR_NAME_S, DT, REC_STATUS,
SYSMOMENT ) VALUES ( 
'BYB', 'Белоруский рубль', 'Белоруский рубль', '01-01-1980', '0',  TO_Date( '12/22/2004 01:13:33 PM', 'MM/DD/YYYY HH:MI:SS AM')); 
INSERT INTO DET_FINSTR ( FINSTR_CODE, FINSTR_NAME, FINSTR_NAME_S, DT, REC_STATUS,
SYSMOMENT ) VALUES ( 
'INR', 'Индийская рупия', 'Индийская рупия', '01-01-1980', '0',  TO_Date( '12/22/2004 01:13:33 PM', 'MM/DD/YYYY HH:MI:SS AM')); 
INSERT INTO DET_FINSTR ( FINSTR_CODE, FINSTR_NAME, FINSTR_NAME_S, DT, REC_STATUS,
SYSMOMENT ) VALUES ( 
'NOK', 'Норвежская крона', 'Норвежская крона', '01-01-1980', '0',  TO_Date( '12/22/2004 01:13:33 PM', 'MM/DD/YYYY HH:MI:SS AM')); 
INSERT INTO DET_FINSTR ( FINSTR_CODE, FINSTR_NAME, FINSTR_NAME_S, DT, REC_STATUS,
SYSMOMENT ) VALUES ( 
'BRC', 'Крузейро', 'Крузейро', '01-01-1980', '0',  TO_Date( '12/22/2004 01:13:33 PM', 'MM/DD/YYYY HH:MI:SS AM')); 
INSERT INTO DET_FINSTR ( FINSTR_CODE, FINSTR_NAME, FINSTR_NAME_S, DT, REC_STATUS,
SYSMOMENT ) VALUES ( 
'BGL', 'Лев', 'Лев', '01-01-1980', '0',  TO_Date( '12/22/2004 01:13:33 PM', 'MM/DD/YYYY HH:MI:SS AM')); 
INSERT INTO DET_FINSTR ( FINSTR_CODE, FINSTR_NAME, FINSTR_NAME_S, DT, REC_STATUS,
SYSMOMENT ) VALUES ( 
'CAD', 'Канадский доллар', 'Канадский доллар', '01-01-1980', '0',  TO_Date( '12/22/2004 01:13:33 PM', 'MM/DD/YYYY HH:MI:SS AM')); 
INSERT INTO DET_FINSTR ( FINSTR_CODE, FINSTR_NAME, FINSTR_NAME_S, DT, REC_STATUS,
SYSMOMENT ) VALUES ( 
'CNY', 'Юань женьминьби', 'Юань женьминьби', '01-01-1980', '0',  TO_Date( '12/22/2004 01:13:33 PM', 'MM/DD/YYYY HH:MI:SS AM')); 
INSERT INTO DET_FINSTR ( FINSTR_CODE, FINSTR_NAME, FINSTR_NAME_S, DT, REC_STATUS,
SYSMOMENT ) VALUES ( 
'CSK', 'Крона', 'Крона', '01-01-1980', '0',  TO_Date( '12/22/2004 01:13:33 PM', 'MM/DD/YYYY HH:MI:SS AM')); 
INSERT INTO DET_FINSTR ( FINSTR_CODE, FINSTR_NAME, FINSTR_NAME_S, DT, REC_STATUS,
SYSMOMENT ) VALUES ( 
'DKK', 'Датская крона', 'Датская крона', '01-01-1980', '0',  TO_Date( '12/22/2004 01:13:33 PM', 'MM/DD/YYYY HH:MI:SS AM')); 
INSERT INTO DET_FINSTR ( FINSTR_CODE, FINSTR_NAME, FINSTR_NAME_S, DT, REC_STATUS,
SYSMOMENT ) VALUES ( 
'EGP', 'Египетский фунт', 'Египетский фунт', '01-01-1980', '0',  TO_Date( '12/22/2004 01:13:33 PM', 'MM/DD/YYYY HH:MI:SS AM')); 
INSERT INTO DET_FINSTR ( FINSTR_CODE, FINSTR_NAME, FINSTR_NAME_S, DT, REC_STATUS,
SYSMOMENT ) VALUES ( 
'FIM', 'Финляндская Марка', 'Финляндская Марка', '01-01-1980', '0',  TO_Date( '12/22/2004 01:13:33 PM', 'MM/DD/YYYY HH:MI:SS AM')); 
INSERT INTO DET_FINSTR ( FINSTR_CODE, FINSTR_NAME, FINSTR_NAME_S, DT, REC_STATUS,
SYSMOMENT ) VALUES ( 
'DEM', 'Немецкая марка', 'Немецкая марка', '01-01-1980', '0',  TO_Date( '12/22/2004 01:13:33 PM', 'MM/DD/YYYY HH:MI:SS AM')); 
INSERT INTO DET_FINSTR ( FINSTR_CODE, FINSTR_NAME, FINSTR_NAME_S, DT, REC_STATUS,
SYSMOMENT ) VALUES ( 
'GRD', 'Греческая драхма', 'Греческая драхма', '01-01-1980', '0',  TO_Date( '12/22/2004 01:13:33 PM', 'MM/DD/YYYY HH:MI:SS AM')); 
INSERT INTO DET_FINSTR ( FINSTR_CODE, FINSTR_NAME, FINSTR_NAME_S, DT, REC_STATUS,
SYSMOMENT ) VALUES ( 
'HKD', 'Гонконгский доллар', 'Гонконгский доллар', '01-01-1980', '0',  TO_Date( '12/22/2004 01:13:33 PM', 'MM/DD/YYYY HH:MI:SS AM')); 
INSERT INTO DET_FINSTR ( FINSTR_CODE, FINSTR_NAME, FINSTR_NAME_S, DT, REC_STATUS,
SYSMOMENT ) VALUES ( 
'ISK', 'Исландская крона', 'Исландская крона', '01-01-1980', '0',  TO_Date( '12/22/2004 01:13:33 PM', 'MM/DD/YYYY HH:MI:SS AM')); 
INSERT INTO DET_FINSTR ( FINSTR_CODE, FINSTR_NAME, FINSTR_NAME_S, DT, REC_STATUS,
SYSMOMENT ) VALUES ( 
'IRR', 'Иранский риал', 'Иранский риал', '01-01-1980', '0',  TO_Date( '12/22/2004 01:13:33 PM', 'MM/DD/YYYY HH:MI:SS AM')); 
INSERT INTO DET_FINSTR ( FINSTR_CODE, FINSTR_NAME, FINSTR_NAME_S, DT, REC_STATUS,
SYSMOMENT ) VALUES ( 
'IEP', 'Ирландский фунт', 'Ирландский фунт', '01-01-1980', '0',  TO_Date( '12/22/2004 01:13:33 PM', 'MM/DD/YYYY HH:MI:SS AM')); 
INSERT INTO DET_FINSTR ( FINSTR_CODE, FINSTR_NAME, FINSTR_NAME_S, DT, REC_STATUS,
SYSMOMENT ) VALUES ( 
'ILS', 'Шекель', 'Шекель', '01-01-1980', '0',  TO_Date( '12/22/2004 01:13:33 PM', 'MM/DD/YYYY HH:MI:SS AM')); 
INSERT INTO DET_FINSTR ( FINSTR_CODE, FINSTR_NAME, FINSTR_NAME_S, DT, REC_STATUS,
SYSMOMENT ) VALUES ( 
'ITL', 'Итальянская лира', 'Итальянская лира', '01-01-1980', '0',  TO_Date( '12/22/2004 01:13:33 PM', 'MM/DD/YYYY HH:MI:SS AM')); 
INSERT INTO DET_FINSTR ( FINSTR_CODE, FINSTR_NAME, FINSTR_NAME_S, DT, REC_STATUS,
SYSMOMENT ) VALUES ( 
'JPY', 'Японская йена', 'Японская йена', '01-01-1980', '0',  TO_Date( '12/22/2004 01:13:33 PM', 'MM/DD/YYYY HH:MI:SS AM')); 
INSERT INTO DET_FINSTR ( FINSTR_CODE, FINSTR_NAME, FINSTR_NAME_S, DT, REC_STATUS,
SYSMOMENT ) VALUES ( 
'CHF', 'Швейцарский франк', 'Швейцарский франк', '01-01-1980', '0',  TO_Date( '12/22/2004 01:13:33 PM', 'MM/DD/YYYY HH:MI:SS AM')); 
INSERT INTO DET_FINSTR ( FINSTR_CODE, FINSTR_NAME, FINSTR_NAME_S, DT, REC_STATUS,
SYSMOMENT ) VALUES ( 
'LUF', 'Люксембургский франк', 'Люксембургский франк', '01-01-1980', '0',  TO_Date( '12/22/2004 01:13:33 PM', 'MM/DD/YYYY HH:MI:SS AM')); 
INSERT INTO DET_FINSTR ( FINSTR_CODE, FINSTR_NAME, FINSTR_NAME_S, DT, REC_STATUS,
SYSMOMENT ) VALUES ( 
'MXP', 'Мексиканское песо', 'Мексиканское песо', '01-01-1980', '0',  TO_Date( '12/22/2004 01:13:33 PM', 'MM/DD/YYYY HH:MI:SS AM')); 
INSERT INTO DET_FINSTR ( FINSTR_CODE, FINSTR_NAME, FINSTR_NAME_S, DT, REC_STATUS,
SYSMOMENT ) VALUES ( 
'MNT', 'Тугрик', 'Тугрик', '01-01-1980', '0',  TO_Date( '12/22/2004 01:13:33 PM', 'MM/DD/YYYY HH:MI:SS AM')); 
INSERT INTO DET_FINSTR ( FINSTR_CODE, FINSTR_NAME, FINSTR_NAME_S, DT, REC_STATUS,
SYSMOMENT ) VALUES ( 
'NLG', 'Нидерландский гульден', 'Нидерландский гульден', '01-01-1980', '0',  TO_Date( '12/22/2004 01:13:33 PM', 'MM/DD/YYYY HH:MI:SS AM')); 
INSERT INTO DET_FINSTR ( FINSTR_CODE, FINSTR_NAME, FINSTR_NAME_S, DT, REC_STATUS,
SYSMOMENT ) VALUES ( 
'NZD', 'Новозеландский доллар', 'Новозеландский доллар', '01-01-1980', '0',  TO_Date( '12/22/2004 01:13:33 PM', 'MM/DD/YYYY HH:MI:SS AM')); 
INSERT INTO DET_FINSTR ( FINSTR_CODE, FINSTR_NAME, FINSTR_NAME_S, DT, REC_STATUS,
SYSMOMENT ) VALUES ( 
'PHP', 'Филиппинское песо', 'Филиппинское песо', '01-01-1980', '0',  TO_Date( '12/22/2004 01:13:33 PM', 'MM/DD/YYYY HH:MI:SS AM')); 
INSERT INTO DET_FINSTR ( FINSTR_CODE, FINSTR_NAME, FINSTR_NAME_S, DT, REC_STATUS,
SYSMOMENT ) VALUES ( 
'PLZ', 'Злотый', 'Злотый', '01-01-1980', '0',  TO_Date( '12/22/2004 01:13:33 PM', 'MM/DD/YYYY HH:MI:SS AM')); 
INSERT INTO DET_FINSTR ( FINSTR_CODE, FINSTR_NAME, FINSTR_NAME_S, DT, REC_STATUS,
SYSMOMENT ) VALUES ( 
'PTE', 'Португальское эскудо', 'Португальское эскудо', '01-01-1980', '0',  TO_Date( '12/22/2004 01:13:33 PM', 'MM/DD/YYYY HH:MI:SS AM')); 
INSERT INTO DET_FINSTR ( FINSTR_CODE, FINSTR_NAME, FINSTR_NAME_S, DT, REC_STATUS,
SYSMOMENT ) VALUES ( 
'ROL', 'Лей', 'Лей', '01-01-1980', '0',  TO_Date( '12/22/2004 01:13:33 PM', 'MM/DD/YYYY HH:MI:SS AM')); 
INSERT INTO DET_FINSTR ( FINSTR_CODE, FINSTR_NAME, FINSTR_NAME_S, DT, REC_STATUS,
SYSMOMENT ) VALUES ( 
'SGD', 'Сингапурский доллар', 'Сингапурский доллар', '01-01-1980', '0',  TO_Date( '12/22/2004 01:13:33 PM', 'MM/DD/YYYY HH:MI:SS AM')); 
INSERT INTO DET_FINSTR ( FINSTR_CODE, FINSTR_NAME, FINSTR_NAME_S, DT, REC_STATUS,
SYSMOMENT ) VALUES ( 
'ZAR', 'Ранд', 'Ранд', '01-01-1980', '0',  TO_Date( '12/22/2004 01:13:33 PM', 'MM/DD/YYYY HH:MI:SS AM')); 
INSERT INTO DET_FINSTR ( FINSTR_CODE, FINSTR_NAME, FINSTR_NAME_S, DT, REC_STATUS,
SYSMOMENT ) VALUES ( 
'SEK', 'Шведская крона', 'Шведская крона', '01-01-1980', '0',  TO_Date( '12/22/2004 01:13:33 PM', 'MM/DD/YYYY HH:MI:SS AM')); 
INSERT INTO DET_FINSTR ( FINSTR_CODE, FINSTR_NAME, FINSTR_NAME_S, DT, REC_STATUS,
SYSMOMENT ) VALUES ( 
'SYP', 'Сирийский фунт', 'Сирийский фунт', '01-01-1980', '0',  TO_Date( '12/22/2004 01:13:33 PM', 'MM/DD/YYYY HH:MI:SS AM')); 
INSERT INTO DET_FINSTR ( FINSTR_CODE, FINSTR_NAME, FINSTR_NAME_S, DT, REC_STATUS,
SYSMOMENT ) VALUES ( 
'TRL', 'Турецкая лира', 'Турецкая лира', '01-01-1980', '0',  TO_Date( '12/22/2004 01:13:33 PM', 'MM/DD/YYYY HH:MI:SS AM')); 
INSERT INTO DET_FINSTR ( FINSTR_CODE, FINSTR_NAME, FINSTR_NAME_S, DT, REC_STATUS,
SYSMOMENT ) VALUES ( 
'AED', 'Дирхам ОАЭ', 'Дирхам ОАЭ', '01-01-1980', '0',  TO_Date( '12/22/2004 01:13:33 PM', 'MM/DD/YYYY HH:MI:SS AM')); 
INSERT INTO DET_FINSTR ( FINSTR_CODE, FINSTR_NAME, FINSTR_NAME_S, DT, REC_STATUS,
SYSMOMENT ) VALUES ( 
'RUR', 'Российский рубль', 'Российский рубль', '01-01-1980', '0',  TO_Date( '12/22/2004 01:13:33 PM', 'MM/DD/YYYY HH:MI:SS AM')); 
INSERT INTO DET_FINSTR ( FINSTR_CODE, FINSTR_NAME, FINSTR_NAME_S, DT, REC_STATUS,
SYSMOMENT ) VALUES ( 
'GBP', 'Английский фунт стерлингов', 'Английский фунт стерлингов', '01-01-1980', '0'
,  TO_Date( '12/22/2004 01:13:33 PM', 'MM/DD/YYYY HH:MI:SS AM')); 
INSERT INTO DET_FINSTR ( FINSTR_CODE, FINSTR_NAME, FINSTR_NAME_S, DT, REC_STATUS,
SYSMOMENT ) VALUES ( 
'UKK', 'Украинские карбованцы', 'Украинские карбованцы', '01-01-1980', '0',  TO_Date( '12/22/2004 01:13:33 PM', 'MM/DD/YYYY HH:MI:SS AM')); 
INSERT INTO DET_FINSTR ( FINSTR_CODE, FINSTR_NAME, FINSTR_NAME_S, DT, REC_STATUS,
SYSMOMENT ) VALUES ( 
'EEK', 'Эстонские кроны', 'Эстонские кроны', '01-01-1980', '0',  TO_Date( '12/22/2004 01:13:33 PM', 'MM/DD/YYYY HH:MI:SS AM')); 
INSERT INTO DET_FINSTR ( FINSTR_CODE, FINSTR_NAME, FINSTR_NAME_S, DT, REC_STATUS,
SYSMOMENT ) VALUES ( 
'LVL', 'Латвийские латы', 'Латвийские латы', '01-01-1980', '0',  TO_Date( '12/22/2004 01:13:33 PM', 'MM/DD/YYYY HH:MI:SS AM')); 
INSERT INTO DET_FINSTR ( FINSTR_CODE, FINSTR_NAME, FINSTR_NAME_S, DT, REC_STATUS,
SYSMOMENT ) VALUES ( 
'LTL', 'Литовские литы', 'Литовские литы', '01-01-1980', '0',  TO_Date( '12/22/2004 01:13:33 PM', 'MM/DD/YYYY HH:MI:SS AM')); 
INSERT INTO DET_FINSTR ( FINSTR_CODE, FINSTR_NAME, FINSTR_NAME_S, DT, REC_STATUS,
SYSMOMENT ) VALUES ( 
'KZT', 'Казахские тенге', 'Казахские тенге', '01-01-1980', '0',  TO_Date( '12/22/2004 01:13:33 PM', 'MM/DD/YYYY HH:MI:SS AM')); 
INSERT INTO DET_FINSTR ( FINSTR_CODE, FINSTR_NAME, FINSTR_NAME_S, DT, REC_STATUS,
SYSMOMENT ) VALUES ( 
'UZS', 'Узбекистанские сум-купоны', 'Узбекистанские сум-купоны', '01-01-1980', '0'
,  TO_Date( '12/22/2004 01:13:33 PM', 'MM/DD/YYYY HH:MI:SS AM')); 
INSERT INTO DET_FINSTR ( FINSTR_CODE, FINSTR_NAME, FINSTR_NAME_S, DT, REC_STATUS,
SYSMOMENT ) VALUES ( 
'AMD', 'Армянские драмы', 'Армянские драмы', '01-01-1980', '0',  TO_Date( '12/22/2004 01:13:33 PM', 'MM/DD/YYYY HH:MI:SS AM')); 
INSERT INTO DET_FINSTR ( FINSTR_CODE, FINSTR_NAME, FINSTR_NAME_S, DT, REC_STATUS,
SYSMOMENT ) VALUES ( 
'HUF', 'Форинт', 'Форинт', '01-01-1980', '0',  TO_Date( '12/22/2004 01:13:33 PM', 'MM/DD/YYYY HH:MI:SS AM')); 
INSERT INTO DET_FINSTR ( FINSTR_CODE, FINSTR_NAME, FINSTR_NAME_S, DT, REC_STATUS,
SYSMOMENT ) VALUES ( 
'PKR', 'Пакистанская рупия', 'Пакистанская рупия', '01-01-1980', '0',  TO_Date( '12/22/2004 01:13:33 PM', 'MM/DD/YYYY HH:MI:SS AM')); 
INSERT INTO DET_FINSTR ( FINSTR_CODE, FINSTR_NAME, FINSTR_NAME_S, DT, REC_STATUS,
SYSMOMENT ) VALUES ( 
'HEU', 'Экю', 'Экю', '01-01-1980', '0',  TO_Date( '12/22/2004 01:13:33 PM', 'MM/DD/YYYY HH:MI:SS AM')); 
INSERT INTO DET_FINSTR ( FINSTR_CODE, FINSTR_NAME, FINSTR_NAME_S, DT, REC_STATUS,
SYSMOMENT ) VALUES ( 
'EUR', 'ЕВРО', 'ЕВРО', '01-01-1980', '0',  TO_Date( '12/22/2004 01:13:33 PM', 'MM/DD/YYYY HH:MI:SS AM')); 
INSERT INTO DET_FINSTR ( FINSTR_CODE, FINSTR_NAME, FINSTR_NAME_S, DT, REC_STATUS,
SYSMOMENT ) VALUES ( 
'BYR', 'Белорусский рубль', 'Белорусский рубль', '01-01-1980', '0',  TO_Date( '12/22/2004 01:13:33 PM', 'MM/DD/YYYY HH:MI:SS AM')); 
INSERT INTO DET_FINSTR ( FINSTR_CODE, FINSTR_NAME, FINSTR_NAME_S, DT, REC_STATUS,
SYSMOMENT ) VALUES ( 
'UAH', 'Украинская гривна', 'Украинская гривна', '01-01-1980', '0',  TO_Date( '12/22/2004 01:13:33 PM', 'MM/DD/YYYY HH:MI:SS AM')); 
INSERT INTO DET_FINSTR ( FINSTR_CODE, FINSTR_NAME, FINSTR_NAME_S, DT, REC_STATUS,
SYSMOMENT ) VALUES ( 
'GEL', 'Грузинские лари', 'Грузинские лари', '01-01-1980', '0',  TO_Date( '12/22/2004 01:13:33 PM', 'MM/DD/YYYY HH:MI:SS AM')); 
INSERT INTO DET_FINSTR ( FINSTR_CODE, FINSTR_NAME, FINSTR_NAME_S, DT, REC_STATUS,
SYSMOMENT ) VALUES ( 
'BEF', 'Бельгийский франк', 'Бельгийский франк', '01-01-1980', '0',  TO_Date( '12/22/2004 01:13:33 PM', 'MM/DD/YYYY HH:MI:SS AM')); 
INSERT INTO DET_FINSTR ( FINSTR_CODE, FINSTR_NAME, FINSTR_NAME_S, DT, REC_STATUS,
SYSMOMENT ) VALUES ( 
'XDI', 'Доллары США по расч. с Индией', 'Доллары США по расч. с Индией', '01-01-1980'
, '0',  TO_Date( '12/22/2004 01:13:33 PM', 'MM/DD/YYYY HH:MI:SS AM')); 
INSERT INTO DET_FINSTR ( FINSTR_CODE, FINSTR_NAME, FINSTR_NAME_S, DT, REC_STATUS,
SYSMOMENT ) VALUES ( 
'TRY', 'Новая турецкая лира', 'Новая турецкая лира', '01-01-1980'
, '0',  TO_Date( '12/22/2004 01:13:33 PM', 'MM/DD/YYYY HH:MI:SS AM')); 
commit;
 
