INSERT INTO DET_BRANCHMSFO ( CODE, NAME, DT, REC_STATUS, REC_UNLOAD, REC_PROCESS,
ID_FILE ) VALUES ( 
'Aluminium industry', 'Aluminium industry', '01-01-1980', '0', 1, 1, NULL); 
INSERT INTO DET_BRANCHMSFO ( CODE, NAME, DT, REC_STATUS, REC_UNLOAD, REC_PROCESS,
ID_FILE ) VALUES ( 
'Chemistry', 'Chemistry', '01-01-1980', '0', 1, 1, NULL); 
INSERT INTO DET_BRANCHMSFO ( CODE, NAME, DT, REC_STATUS, REC_UNLOAD, REC_PROCESS,
ID_FILE ) VALUES ( 
'Coal', 'Coal', '01-01-1980', '0', 1, 1, NULL); 
INSERT INTO DET_BRANCHMSFO ( CODE, NAME, DT, REC_STATUS, REC_UNLOAD, REC_PROCESS,
ID_FILE ) VALUES ( 
'Construction', 'Construction', '01-01-1980', '0', 1, 1, NULL); 
INSERT INTO DET_BRANCHMSFO ( CODE, NAME, DT, REC_STATUS, REC_UNLOAD, REC_PROCESS,
ID_FILE ) VALUES ( 
'Energy', 'Energy', '01-01-1980', '0', 1, 1, NULL); 
INSERT INTO DET_BRANCHMSFO ( CODE, NAME, DT, REC_STATUS, REC_UNLOAD, REC_PROCESS,
ID_FILE ) VALUES ( 
'Finance', 'Finance', '01-01-1980', '0', 1, 1, NULL); 
INSERT INTO DET_BRANCHMSFO ( CODE, NAME, DT, REC_STATUS, REC_UNLOAD, REC_PROCESS,
ID_FILE ) VALUES ( 
'Food and agricultu', 'Food and agricultur', '01-01-1980', '0', 1, 1, NULL); 
INSERT INTO DET_BRANCHMSFO ( CODE, NAME, DT, REC_STATUS, REC_UNLOAD, REC_PROCESS,
ID_FILE ) VALUES ( 
'Manufacturing', 'Manufacturing', '01-01-1980', '0', 1, 1, NULL); 
INSERT INTO DET_BRANCHMSFO ( CODE, NAME, DT, REC_STATUS, REC_UNLOAD, REC_PROCESS,
ID_FILE ) VALUES ( 
'Metallurgy', 'Metallurgy', '01-01-1980', '0', 1, 1, NULL); 
INSERT INTO DET_BRANCHMSFO ( CODE, NAME, DT, REC_STATUS, REC_UNLOAD, REC_PROCESS,
ID_FILE ) VALUES ( 
'Oil and gas', 'Oil and gas', '01-01-1980', '0', 1, 1, NULL); 
INSERT INTO DET_BRANCHMSFO ( CODE, NAME, DT, REC_STATUS, REC_UNLOAD, REC_PROCESS,
ID_FILE ) VALUES ( 
'Ore exploration', 'Ore exploration', '01-01-1980', '0', 1, 1, NULL); 
INSERT INTO DET_BRANCHMSFO ( CODE, NAME, DT, REC_STATUS, REC_UNLOAD, REC_PROCESS,
ID_FILE ) VALUES ( 
'Other', 'Other', '01-01-1980', '0', 1, 1, NULL); 
INSERT INTO DET_BRANCHMSFO ( CODE, NAME, DT, REC_STATUS, REC_UNLOAD, REC_PROCESS,
ID_FILE ) VALUES ( 
'Real estate', 'Real estate', '01-01-1980', '0', 1, 1, NULL); 
INSERT INTO DET_BRANCHMSFO ( CODE, NAME, DT, REC_STATUS, REC_UNLOAD, REC_PROCESS,
ID_FILE ) VALUES ( 
'Regional admin', 'Regional admin', '01-01-1980', '0', 1, 1, NULL); 
INSERT INTO DET_BRANCHMSFO ( CODE, NAME, DT, REC_STATUS, REC_UNLOAD, REC_PROCESS,
ID_FILE ) VALUES ( 
'Trade', 'Trade', '01-01-1980', '0', 1, 1, NULL); 
INSERT INTO DET_BRANCHMSFO ( CODE, NAME, DT, REC_STATUS, REC_UNLOAD, REC_PROCESS,
ID_FILE ) VALUES ( 
'Transport', 'Transport', '01-01-1980', '0', 1, 1, NULL); 
INSERT INTO DET_BRANCHMSFO ( CODE, NAME, DT, REC_STATUS, REC_UNLOAD, REC_PROCESS,
ID_FILE ) VALUES ( 
'Retail&consumer', 'Retail&consumer', '01-01-1980', '0', 1, 1, NULL); 
INSERT INTO DET_BRANCHMSFO ( CODE, NAME, DT, REC_STATUS, REC_UNLOAD, REC_PROCESS,
ID_FILE ) VALUES ( 
'Government', 'Government', '01-01-1980', '0', 1, 1, NULL); 
INSERT INTO DET_BRANCHMSFO ( CODE, NAME, DT, REC_STATUS, REC_UNLOAD, REC_PROCESS,
ID_FILE ) VALUES ( 
'Communication', 'Communication', '01-01-1980', '0', 1, 1, NULL); 
INSERT INTO DET_BRANCHMSFO ( CODE, NAME, DT, REC_STATUS, REC_UNLOAD, REC_PROCESS,
ID_FILE ) VALUES ( 
'-1', 'Не указан', '01-01-1980', '0', 1, 1, NULL); 
COMMIT;
