INSERT INTO DET_CHAPTER ( CHAPTER_CODE, CHAPTER_NAME, DT, REC_STATUS, REC_UNLOAD, REC_PROCESS,
ID_FILE ) VALUES ( 
'А', 'Балансовые счета', '01-01-1980', '0', NULL, NULL, NULL); 
INSERT INTO DET_CHAPTER ( CHAPTER_CODE, CHAPTER_NAME, DT, REC_STATUS, REC_UNLOAD, REC_PROCESS,
ID_FILE ) VALUES ( 
'Б', 'Счета доверитедьного управления', '01-01-1980', '0', NULL, NULL, NULL); 
INSERT INTO DET_CHAPTER ( CHAPTER_CODE, CHAPTER_NAME, DT, REC_STATUS, REC_UNLOAD, REC_PROCESS,
ID_FILE ) VALUES ( 
'В', 'Внебалансовые счета', '01-01-1980', '0', NULL, NULL, NULL); 
INSERT INTO DET_CHAPTER ( CHAPTER_CODE, CHAPTER_NAME, DT, REC_STATUS, REC_UNLOAD, REC_PROCESS,
ID_FILE ) VALUES ( 
'Г', 'Срочные операции', '01-01-1980', '0', NULL, NULL, NULL); 
INSERT INTO DET_CHAPTER ( CHAPTER_CODE, CHAPTER_NAME, DT, REC_STATUS, REC_UNLOAD, REC_PROCESS,
ID_FILE ) VALUES ( 
'Д', 'Счета депозитарного учета', '01-01-1980', '0', NULL, NULL, NULL); 
COMMIT;
