INSERT INTO DET_TYPEATTR ( CODE, NAME, DT, REC_STATUS, REC_UNLOAD, REC_PROCESS,
ID_FILE ) VALUES ( 
'IDMDM', 'Код IDMDM', '01-01-1980', '0', 1, 1, NULL); 
INSERT INTO DET_TYPEATTR ( CODE, NAME, DT, REC_STATUS, REC_UNLOAD, REC_PROCESS,
ID_FILE ) VALUES ( 
'INN', 'ИНН клиента', '01-01-1980', '0', 1, 1, NULL); 
INSERT INTO DET_TYPEATTR ( CODE, NAME, DT, REC_STATUS, REC_UNLOAD, REC_PROCESS,
ID_FILE ) VALUES ( 
'SystemID', 'ID клиента в учётной системе', '01-01-1980', '0', 1, 1, NULL); 
INSERT INTO DET_TYPEATTR ( CODE, NAME, DT, REC_STATUS, REC_UNLOAD, REC_PROCESS,
ID_FILE ) VALUES ( 
'SystemCode', 'Код клиента в учётной системе', '01-01-1980', '0', 1, 1, NULL); 
INSERT INTO DET_TYPEATTR ( CODE, NAME, DT, REC_STATUS, REC_UNLOAD, REC_PROCESS,
ID_FILE ) VALUES ( 
'AtheneDoc', 'Client.Doc клиента в ИБС "Афина"', '01-01-1980', '0', 1, 1, NULL); 
INSERT INTO DET_TYPEATTR ( CODE, NAME, DT, REC_STATUS, REC_UNLOAD, REC_PROCESS,
ID_FILE ) VALUES ( 
'AtheneClassified', 'Client.Classified клиента в ИБС "Афина"', '01-01-1980', '0', 1
, 1, NULL); 
INSERT INTO DET_TYPEATTR ( CODE, NAME, DT, REC_STATUS, REC_UNLOAD, REC_PROCESS,
ID_FILE ) VALUES ( 
'SWIFT', 'код SWIFT', '01-01-1980', '0', 1, 1, NULL); 
INSERT INTO DET_TYPEATTR ( CODE, NAME, DT, REC_STATUS, REC_UNLOAD, REC_PROCESS,
ID_FILE ) VALUES ( 
'BIK', 'код БИК', '01-01-1980', '0', 1, 1, NULL); 
INSERT INTO DET_TYPEATTR ( CODE, NAME, DT, REC_STATUS, REC_UNLOAD, REC_PROCESS,
ID_FILE ) VALUES ( 
'ShortNameMBW', 'код ShortName-МДМ', '01-01-1980', '0', 1, 1, NULL); 
COMMIT;
