INSERT INTO DET_TYPELINKGROUP ( CODE_SUBJECTLINK, NAMELINK, DT, REC_STATUS, REC_UNLOAD, REC_PROCESS,
ID_FILE ) VALUES ( 
'LinkClients', 'Группа связанных клиентов', '01-01-1980', '0', 1, 1, NULL); 
COMMIT;
