Insert into ASS_PLAN_DEP(DT, DEPARTMENT_CODE, PLAN_BAL_CODE, REC_STATUS, REC_UNLOAD, REC_PROCESS)
Values('01-01-1980', 'MDM_SPb', 'BANK_RUR', '0', 1, 1);
Insert into ASS_PLAN_DEP(DT, DEPARTMENT_CODE, PLAN_BAL_CODE, REC_STATUS, REC_UNLOAD, REC_PROCESS)
Values('01-01-1980', 'MDM_SPbG', 'BANK_RUR', '0', 1, 1);
Insert into ASS_PLAN_DEP(DT, DEPARTMENT_CODE, PLAN_BAL_CODE, REC_STATUS, REC_UNLOAD, REC_PROCESS)
Values('01-01-1980', 'MDM_SPbO', 'BANK_RUR', '0', 1, 1);
