INSERT INTO ASS_BANK_DEPARTMENT ( DT, PARENT_CODE_DEPARTMENT, CHILD_CODE_DEPARTMENT, REC_STATUS,
REC_UNLOAD, REC_PROCESS, ID_FILE ) VALUES ( 
'19800101', 'MDM_SPb', 'MDM_SPbG', '0', 1, 1, NULL); 
INSERT INTO ASS_BANK_DEPARTMENT ( DT, PARENT_CODE_DEPARTMENT, CHILD_CODE_DEPARTMENT, REC_STATUS,
REC_UNLOAD, REC_PROCESS, ID_FILE ) VALUES ( 
'19800101', 'MDM_SPb', 'MDM_SPbO', '0', 1, 1, NULL); 
COMMIT;
