INSERT INTO BP_TABLEDEF ( TBLNAME, FLDNAME, FLDNAMEDBF, UNLOAD ) VALUES ( 
'DET_SUBJECT', 'CODE_SUBJECT', 'Field2', 1); 
INSERT INTO BP_TABLEDEF ( TBLNAME, FLDNAME, FLDNAMEDBF, UNLOAD ) VALUES ( 
'DET_SUBJECT', 'ID_MDM', 'Field3', 1); 
INSERT INTO BP_TABLEDEF ( TBLNAME, FLDNAME, FLDNAMEDBF, UNLOAD ) VALUES ( 
'DET_SUBJECT', 'DT', 'Field4', 1); 
INSERT INTO BP_TABLEDEF ( TBLNAME, FLDNAME, FLDNAMEDBF, UNLOAD ) VALUES ( 
'DET_SUBJECT', 'SYSTEM_CODE', 'Field5', 1); 
INSERT INTO BP_TABLEDEF ( TBLNAME, FLDNAME, FLDNAMEDBF, UNLOAD ) VALUES ( 
'DET_SUBJECT', 'DEPARTMENT_CODE', 'Field6', 1); 
INSERT INTO BP_TABLEDEF ( TBLNAME, FLDNAME, FLDNAMEDBF, UNLOAD ) VALUES ( 
'DET_SUBJECT', 'COUNTRY_CODE_NUM', 'Field7', 1); 
INSERT INTO BP_TABLEDEF ( TBLNAME, FLDNAME, FLDNAMEDBF, UNLOAD ) VALUES ( 
'DET_SUBJECT', 'CFA_CODE', 'Field8', 1); 
INSERT INTO BP_TABLEDEF ( TBLNAME, FLDNAME, FLDNAMEDBF, UNLOAD ) VALUES ( 
'DET_SUBJECT', 'BRANCHMSFO_CODE', 'Field9', 1); 
INSERT INTO BP_TABLEDEF ( TBLNAME, FLDNAME, FLDNAMEDBF, UNLOAD ) VALUES ( 
'DET_SUBJECT', 'REC_STATUS', 'Field10', 1); 
INSERT INTO BP_TABLEDEF ( TBLNAME, FLDNAME, FLDNAMEDBF, UNLOAD ) VALUES ( 
'DET_JURIDIC_PERSON', 'JURIDIC_PERSON_NAME_S', 'Field1', 1); 
INSERT INTO BP_TABLEDEF ( TBLNAME, FLDNAME, FLDNAMEDBF, UNLOAD ) VALUES ( 
'DET_SUBJECT', 'SUBJECT_INN', 'Field1', 1); 
INSERT INTO BP_TABLEDEF ( TBLNAME, FLDNAME, FLDNAMEDBF, UNLOAD ) VALUES ( 
'DET_JURIDIC_PERSON', 'JURIDIC_PERSON_NAME', 'Field2', 1); 
INSERT INTO BP_TABLEDEF ( TBLNAME, FLDNAME, FLDNAMEDBF, UNLOAD ) VALUES ( 
'DET_JURIDIC_PERSON', 'DT', 'Field3', 1); 
INSERT INTO BP_TABLEDEF ( TBLNAME, FLDNAME, FLDNAMEDBF, UNLOAD ) VALUES ( 
'DET_JURIDIC_PERSON', 'SUBJECT_CODE', 'Field4', 1); 
INSERT INTO BP_TABLEDEF ( TBLNAME, FLDNAME, FLDNAMEDBF, UNLOAD ) VALUES ( 
'DET_JURIDIC_PERSON', 'OKVED_CODE', 'Field5', 1); 
INSERT INTO BP_TABLEDEF ( TBLNAME, FLDNAME, FLDNAMEDBF, UNLOAD ) VALUES ( 
'DET_JURIDIC_PERSON', 'OKATO_CODE', 'Field6', 1); 
INSERT INTO BP_TABLEDEF ( TBLNAME, FLDNAME, FLDNAMEDBF, UNLOAD ) VALUES ( 
'DET_JURIDIC_PERSON', 'REC_STATUS', 'Field7', 1); 
INSERT INTO BP_TABLEDEF ( TBLNAME, FLDNAME, FLDNAMEDBF, UNLOAD ) VALUES ( 
'DET_PHYZ_PERSON', 'IS_INSIDER', 'Field1', 1); 
INSERT INTO BP_TABLEDEF ( TBLNAME, FLDNAME, FLDNAMEDBF, UNLOAD ) VALUES ( 
'DET_PHYZ_PERSON', 'PERSON_NAME', 'Field2', 1); 
INSERT INTO BP_TABLEDEF ( TBLNAME, FLDNAME, FLDNAMEDBF, UNLOAD ) VALUES ( 
'DET_PHYZ_PERSON', 'DOCUMENT_KIND', 'Field3', 1); 
INSERT INTO BP_TABLEDEF ( TBLNAME, FLDNAME, FLDNAMEDBF, UNLOAD ) VALUES ( 
'DET_PHYZ_PERSON', 'DOCUMENT_SER', 'Field4', 1); 
INSERT INTO BP_TABLEDEF ( TBLNAME, FLDNAME, FLDNAMEDBF, UNLOAD ) VALUES ( 
'DET_PHYZ_PERSON', 'DOCUMENT_NUMB', 'Field5', 1); 
INSERT INTO BP_TABLEDEF ( TBLNAME, FLDNAME, FLDNAMEDBF, UNLOAD ) VALUES ( 
'DET_PHYZ_PERSON', 'DOCUMENT_DATA_ISSUE', 'Field6', 1); 
INSERT INTO BP_TABLEDEF ( TBLNAME, FLDNAME, FLDNAMEDBF, UNLOAD ) VALUES ( 
'DET_PHYZ_PERSON', 'DT', 'Field7', 1); 
INSERT INTO BP_TABLEDEF ( TBLNAME, FLDNAME, FLDNAMEDBF, UNLOAD ) VALUES ( 
'DET_PHYZ_PERSON', 'SUBJECT_CODE', 'Field8', 1); 
INSERT INTO BP_TABLEDEF ( TBLNAME, FLDNAME, FLDNAMEDBF, UNLOAD ) VALUES ( 
'DET_PHYZ_PERSON', 'REC_STATUS', 'Field9', 1); 
INSERT INTO BP_TABLEDEF ( TBLNAME, FLDNAME, FLDNAMEDBF, UNLOAD ) VALUES ( 
'DET_ACCOUNT', 'IS_INCONSOLIDATE', 'Field1', 1); 
INSERT INTO BP_TABLEDEF ( TBLNAME, FLDNAME, FLDNAMEDBF, UNLOAD ) VALUES ( 
'DET_ACCOUNT', 'DT_OPEN_ACC', 'Field2', 1); 
INSERT INTO BP_TABLEDEF ( TBLNAME, FLDNAME, FLDNAMEDBF, UNLOAD ) VALUES ( 
'DET_ACCOUNT', 'DT_CLOSE_ACC', 'Field3', 1); 
INSERT INTO BP_TABLEDEF ( TBLNAME, FLDNAME, FLDNAMEDBF, UNLOAD ) VALUES ( 
'DET_ACCOUNT', 'DT', 'Field4', 1); 
INSERT INTO BP_TABLEDEF ( TBLNAME, FLDNAME, FLDNAMEDBF, UNLOAD ) VALUES ( 
'DET_ACCOUNT', 'SYSTEM_CODE', 'Field5', 1); 
INSERT INTO BP_TABLEDEF ( TBLNAME, FLDNAME, FLDNAMEDBF, UNLOAD ) VALUES ( 
'DET_ACCOUNT', 'SUBJECT_CODE', 'Field6', 1); 
INSERT INTO BP_TABLEDEF ( TBLNAME, FLDNAME, FLDNAMEDBF, UNLOAD ) VALUES ( 
'DET_ACCOUNT', 'FINSTR_CODE', 'Field7', 1); 
INSERT INTO BP_TABLEDEF ( TBLNAME, FLDNAME, FLDNAMEDBF, UNLOAD ) VALUES ( 
'DET_ACCOUNT', 'DEPARTMENT_CODE', 'Field8', 1); 
INSERT INTO BP_TABLEDEF ( TBLNAME, FLDNAME, FLDNAMEDBF, UNLOAD ) VALUES ( 
'DET_ACCOUNT', 'CURRENCY_CURR_CODE_TXT', 'Field9', 1); 
INSERT INTO BP_TABLEDEF ( TBLNAME, FLDNAME, FLDNAMEDBF, UNLOAD ) VALUES ( 
'DET_ACCOUNT', 'CHAPTER_CODE', 'Field10', 1); 
INSERT INTO BP_TABLEDEF ( TBLNAME, FLDNAME, FLDNAMEDBF, UNLOAD ) VALUES ( 
'DET_ACCOUNT', 'REC_STATUS', 'Field11', 1); 
INSERT INTO BP_TABLEDEF ( TBLNAME, FLDNAME, FLDNAMEDBF, UNLOAD ) VALUES ( 
'DET_ACCOUNT', 'CODE', 'Field12', 1); 
INSERT INTO BP_TABLEDEF ( TBLNAME, FLDNAME, FLDNAMEDBF, UNLOAD ) VALUES ( 
'DET_ACCOUNT', 'ACCOUNT_NUMBER', 'Field13', 1); 
INSERT INTO BP_TABLEDEF ( TBLNAME, FLDNAME, FLDNAMEDBF, UNLOAD ) VALUES ( 
'DET_ACCOUNT', 'ACCOUNT_NAME', 'Field14', 1); 
INSERT INTO BP_TABLEDEF ( TBLNAME, FLDNAME, FLDNAMEDBF, UNLOAD ) VALUES ( 
'ASS_ACCOUNT_BALANCE', 'DT', 'Field1', 1); 
INSERT INTO BP_TABLEDEF ( TBLNAME, FLDNAME, FLDNAMEDBF, UNLOAD ) VALUES ( 
'ASS_ACCOUNT_BALANCE', 'ACCOUNT_CODE', 'Field2', 1); 
INSERT INTO BP_TABLEDEF ( TBLNAME, FLDNAME, FLDNAMEDBF, UNLOAD ) VALUES ( 
'ASS_ACCOUNT_BALANCE', 'BALANCE_CODE', 'Field3', 1); 
INSERT INTO BP_TABLEDEF ( TBLNAME, FLDNAME, FLDNAMEDBF, UNLOAD ) VALUES ( 
'FCT_CARRY', 'SYSMOMENT', 'Field12', 1); 
INSERT INTO BP_TABLEDEF ( TBLNAME, FLDNAME, FLDNAMEDBF, UNLOAD ) VALUES ( 
'ASS_ACCOUNT_BALANCE', 'BALANCE_PLAN_BAL_CODE', 'Field5', 1); 
INSERT INTO BP_TABLEDEF ( TBLNAME, FLDNAME, FLDNAMEDBF, UNLOAD ) VALUES ( 
'ASS_ACCOUNT_BALANCE', 'REC_STATUS', 'Field6', 1); 
INSERT INTO BP_TABLEDEF ( TBLNAME, FLDNAME, FLDNAMEDBF, UNLOAD ) VALUES ( 
'ASS_SUBJECT_CAT', 'DT', 'Field1', 1); 
INSERT INTO BP_TABLEDEF ( TBLNAME, FLDNAME, FLDNAMEDBF, UNLOAD ) VALUES ( 
'ASS_SUBJECT_CAT', 'SUBJECT_CODE', 'Field2', 1); 
INSERT INTO BP_TABLEDEF ( TBLNAME, FLDNAME, FLDNAMEDBF, UNLOAD ) VALUES ( 
'ASS_SUBJECT_CAT', 'SUBJECT_CAT_VAL_CODE', 'Field3', 1); 
INSERT INTO BP_TABLEDEF ( TBLNAME, FLDNAME, FLDNAMEDBF, UNLOAD ) VALUES ( 
'ASS_SUBJECT_CAT', 'SUBJECT_CAT_VAL_SUBJECT_CAT_CO', 'Field4', 1); 
INSERT INTO BP_TABLEDEF ( TBLNAME, FLDNAME, FLDNAMEDBF, UNLOAD ) VALUES ( 
'ASS_SUBJECT_CAT', 'REC_STATUS', 'Field5', 1); 
INSERT INTO BP_TABLEDEF ( TBLNAME, FLDNAME, FLDNAMEDBF, UNLOAD ) VALUES ( 
'FCT_CARRY', 'CODE', 'Field1', 1); 
INSERT INTO BP_TABLEDEF ( TBLNAME, FLDNAME, FLDNAMEDBF, UNLOAD ) VALUES ( 
'FCT_CARRY', 'VALUE', 'Field2', 1); 
INSERT INTO BP_TABLEDEF ( TBLNAME, FLDNAME, FLDNAMEDBF, UNLOAD ) VALUES ( 
'FCT_CARRY', 'VALUE_NAT', 'Field3', 1); 
INSERT INTO BP_TABLEDEF ( TBLNAME, FLDNAME, FLDNAMEDBF, UNLOAD ) VALUES ( 
'FCT_CARRY', 'DOCNUM', 'Field4', 1); 
INSERT INTO BP_TABLEDEF ( TBLNAME, FLDNAME, FLDNAMEDBF, UNLOAD ) VALUES ( 
'FCT_CARRY', 'CARRY_GROUND', 'Field5', 1); 
INSERT INTO BP_TABLEDEF ( TBLNAME, FLDNAME, FLDNAMEDBF, UNLOAD ) VALUES ( 
'FCT_CARRY', 'DT', 'Field6', 1); 
INSERT INTO BP_TABLEDEF ( TBLNAME, FLDNAME, FLDNAMEDBF, UNLOAD ) VALUES ( 
'FCT_CARRY', 'ROLECREDIT_CODE', 'Field7', 1); 
INSERT INTO BP_TABLEDEF ( TBLNAME, FLDNAME, FLDNAMEDBF, UNLOAD ) VALUES ( 
'FCT_CARRY', 'ROLEDEBET_CODE', 'Field8', 1); 
INSERT INTO BP_TABLEDEF ( TBLNAME, FLDNAME, FLDNAMEDBF, UNLOAD ) VALUES ( 
'FCT_CARRY', 'ACCOUNT_CREDIT_CODE', 'Field9', 1); 
INSERT INTO BP_TABLEDEF ( TBLNAME, FLDNAME, FLDNAMEDBF, UNLOAD ) VALUES ( 
'FCT_CARRY', 'ACCOUNT_DEBET_CODE', 'Field10', 1); 
INSERT INTO BP_TABLEDEF ( TBLNAME, FLDNAME, FLDNAMEDBF, UNLOAD ) VALUES ( 
'FCT_CARRY', 'REC_STATUS', 'Field11', 1); 
INSERT INTO BP_TABLEDEF ( TBLNAME, FLDNAME, FLDNAMEDBF, UNLOAD ) VALUES ( 
'FCT_HALFCARRY', 'CODE', 'Field1', 1); 
INSERT INTO BP_TABLEDEF ( TBLNAME, FLDNAME, FLDNAMEDBF, UNLOAD ) VALUES ( 
'FCT_HALFCARRY', 'VALUE', 'Field2', 1); 
INSERT INTO BP_TABLEDEF ( TBLNAME, FLDNAME, FLDNAMEDBF, UNLOAD ) VALUES ( 
'FCT_HALFCARRY', 'VALUE_NAT', 'Field3', 1); 
INSERT INTO BP_TABLEDEF ( TBLNAME, FLDNAME, FLDNAMEDBF, UNLOAD ) VALUES ( 
'FCT_HALFCARRY', 'DOCNUM', 'Field4', 1); 
INSERT INTO BP_TABLEDEF ( TBLNAME, FLDNAME, FLDNAMEDBF, UNLOAD ) VALUES ( 
'FCT_HALFCARRY', 'HALFCARRY_GROUND', 'Field5', 1); 
INSERT INTO BP_TABLEDEF ( TBLNAME, FLDNAME, FLDNAMEDBF, UNLOAD ) VALUES ( 
'FCT_HALFCARRY', 'DT', 'Field6', 1); 
INSERT INTO BP_TABLEDEF ( TBLNAME, FLDNAME, FLDNAMEDBF, UNLOAD ) VALUES ( 
'FCT_HALFCARRY', 'ROLEACCOUNT_DEAL_CODE', 'Field7', 1); 
INSERT INTO BP_TABLEDEF ( TBLNAME, FLDNAME, FLDNAMEDBF, UNLOAD ) VALUES ( 
'FCT_HALFCARRY', 'ACCOUNT_CODE', 'Field8', 1); 
INSERT INTO BP_TABLEDEF ( TBLNAME, FLDNAME, FLDNAMEDBF, UNLOAD ) VALUES ( 
'FCT_HALFCARRY', 'REC_STATUS', 'Field9', 1); 
INSERT INTO BP_TABLEDEF ( TBLNAME, FLDNAME, FLDNAMEDBF, UNLOAD ) VALUES ( 
'FCT_PAYMENT', 'PAYDATE', 'Field1', 1); 
INSERT INTO BP_TABLEDEF ( TBLNAME, FLDNAME, FLDNAMEDBF, UNLOAD ) VALUES ( 
'FCT_PAYMENT', 'RECSUM', 'Field2', 1); 
INSERT INTO BP_TABLEDEF ( TBLNAME, FLDNAME, FLDNAMEDBF, UNLOAD ) VALUES ( 
'FCT_PAYMENT', 'RECDATE', 'Field3', 1); 
INSERT INTO BP_TABLEDEF ( TBLNAME, FLDNAME, FLDNAMEDBF, UNLOAD ) VALUES ( 
'FCT_PAYMENT', 'PAYNUM', 'Field4', 1); 
INSERT INTO BP_TABLEDEF ( TBLNAME, FLDNAME, FLDNAMEDBF, UNLOAD ) VALUES ( 
'FCT_PAYMENT', 'PAYGROUND', 'Field5', 1); 
INSERT INTO BP_TABLEDEF ( TBLNAME, FLDNAME, FLDNAMEDBF, UNLOAD ) VALUES ( 
'FCT_PAYMENT', 'DOCDATE', 'Field6', 1); 
INSERT INTO BP_TABLEDEF ( TBLNAME, FLDNAME, FLDNAMEDBF, UNLOAD ) VALUES ( 
'FCT_PAYMENT', 'PAYSUM', 'Field7', 1); 
INSERT INTO BP_TABLEDEF ( TBLNAME, FLDNAME, FLDNAMEDBF, UNLOAD ) VALUES ( 
'FCT_PAYMENT', 'SUBJECT_CODE', 'Field8', 1); 
INSERT INTO BP_TABLEDEF ( TBLNAME, FLDNAME, FLDNAMEDBF, UNLOAD ) VALUES ( 
'FCT_PAYMENT', 'PAYFINSTR_FINSTR_CODE', 'Field9', 1); 
INSERT INTO BP_TABLEDEF ( TBLNAME, FLDNAME, FLDNAMEDBF, UNLOAD ) VALUES ( 
'FCT_PAYMENT', 'RECFINSTR_FINSTR_CODE', 'Field10', 1); 
INSERT INTO BP_TABLEDEF ( TBLNAME, FLDNAME, FLDNAMEDBF, UNLOAD ) VALUES ( 
'FCT_CLPAYMENT', 'PAYACCOUNT', 'Field1', 1); 
INSERT INTO BP_TABLEDEF ( TBLNAME, FLDNAME, FLDNAMEDBF, UNLOAD ) VALUES ( 
'FCT_CLPAYMENT', 'PAYNAME', 'Field2', 1); 
INSERT INTO BP_TABLEDEF ( TBLNAME, FLDNAME, FLDNAMEDBF, UNLOAD ) VALUES ( 
'FCT_CLPAYMENT', 'PAYINN', 'Field3', 1); 
INSERT INTO BP_TABLEDEF ( TBLNAME, FLDNAME, FLDNAMEDBF, UNLOAD ) VALUES ( 
'FCT_CLPAYMENT', 'PAYKPP', 'Field4', 1); 
INSERT INTO BP_TABLEDEF ( TBLNAME, FLDNAME, FLDNAMEDBF, UNLOAD ) VALUES ( 
'FCT_CLPAYMENT', 'PAYSWIFT', 'Field5', 1); 
INSERT INTO BP_TABLEDEF ( TBLNAME, FLDNAME, FLDNAMEDBF, UNLOAD ) VALUES ( 
'FCT_CLPAYMENT', 'PAYCOUNTRY', 'Field6', 1); 
INSERT INTO BP_TABLEDEF ( TBLNAME, FLDNAME, FLDNAMEDBF, UNLOAD ) VALUES ( 
'FCT_CLPAYMENT', 'PAYADDRESS', 'Field7', 1); 
INSERT INTO BP_TABLEDEF ( TBLNAME, FLDNAME, FLDNAMEDBF, UNLOAD ) VALUES ( 
'FCT_CLPAYMENT', 'PAYBANKACCOUNT', 'Field8', 1); 
INSERT INTO BP_TABLEDEF ( TBLNAME, FLDNAME, FLDNAMEDBF, UNLOAD ) VALUES ( 
'FCT_CLPAYMENT', 'PAYBANKNAME', 'Field9', 1); 
INSERT INTO BP_TABLEDEF ( TBLNAME, FLDNAME, FLDNAMEDBF, UNLOAD ) VALUES ( 
'FCT_CLPAYMENT', 'PAYBANKBIC', 'Field10', 1); 
INSERT INTO BP_TABLEDEF ( TBLNAME, FLDNAME, FLDNAMEDBF, UNLOAD ) VALUES ( 
'FCT_CLPAYMENT', 'PAYBANKSWIFT', 'Field11', 1); 
INSERT INTO BP_TABLEDEF ( TBLNAME, FLDNAME, FLDNAMEDBF, UNLOAD ) VALUES ( 
'FCT_CLPAYMENT', 'PAYBANKCOUNTRY', 'Field12', 1); 
INSERT INTO BP_TABLEDEF ( TBLNAME, FLDNAME, FLDNAMEDBF, UNLOAD ) VALUES ( 
'FCT_CLPAYMENT', 'RECACCOUNT', 'Field13', 1); 
INSERT INTO BP_TABLEDEF ( TBLNAME, FLDNAME, FLDNAMEDBF, UNLOAD ) VALUES ( 
'FCT_CLPAYMENT', 'RECNAME', 'Field14', 1); 
INSERT INTO BP_TABLEDEF ( TBLNAME, FLDNAME, FLDNAMEDBF, UNLOAD ) VALUES ( 
'FCT_CLPAYMENT', 'RECBANKACCOUNT', 'Field15', 1); 
INSERT INTO BP_TABLEDEF ( TBLNAME, FLDNAME, FLDNAMEDBF, UNLOAD ) VALUES ( 
'FCT_CLPAYMENT', 'RECBANKNAME', 'Field16', 1); 
INSERT INTO BP_TABLEDEF ( TBLNAME, FLDNAME, FLDNAMEDBF, UNLOAD ) VALUES ( 
'FCT_CLPAYMENT', 'RECBANKBIC', 'Field17', 1); 
INSERT INTO BP_TABLEDEF ( TBLNAME, FLDNAME, FLDNAMEDBF, UNLOAD ) VALUES ( 
'FCT_CLPAYMENT', 'RECBANKSWIFT', 'Field18', 1); 
INSERT INTO BP_TABLEDEF ( TBLNAME, FLDNAME, FLDNAMEDBF, UNLOAD ) VALUES ( 
'FCT_CLPAYMENT', 'RECBANKCOUNTRY', 'Field19', 1); 
INSERT INTO BP_TABLEDEF ( TBLNAME, FLDNAME, FLDNAMEDBF, UNLOAD ) VALUES ( 
'FCT_CLPAYMENT', 'REC_STATUS', 'Field21', 1); 
INSERT INTO BP_TABLEDEF ( TBLNAME, FLDNAME, FLDNAMEDBF, UNLOAD ) VALUES ( 
'FCT_ASSETS', 'CODE', 'Field1', 1); 
INSERT INTO BP_TABLEDEF ( TBLNAME, FLDNAME, FLDNAMEDBF, UNLOAD ) VALUES ( 
'FCT_ASSETS', 'NAME', 'Field2', 1); 
INSERT INTO BP_TABLEDEF ( TBLNAME, FLDNAME, FLDNAMEDBF, UNLOAD ) VALUES ( 
'FCT_ASSETS', 'IS_COMPLETE', 'Field3', 1); 
INSERT INTO BP_TABLEDEF ( TBLNAME, FLDNAME, FLDNAMEDBF, UNLOAD ) VALUES ( 
'FCT_ASSETS', 'PAYDATE', 'Field4', 1); 
INSERT INTO BP_TABLEDEF ( TBLNAME, FLDNAME, FLDNAMEDBF, UNLOAD ) VALUES ( 
'FCT_ASSETS', 'OPERDATE', 'Field5', 1); 
INSERT INTO BP_TABLEDEF ( TBLNAME, FLDNAME, FLDNAMEDBF, UNLOAD ) VALUES ( 
'FCT_ASSETS', 'ENDDATE', 'Field6', 1); 
INSERT INTO BP_TABLEDEF ( TBLNAME, FLDNAME, FLDNAMEDBF, UNLOAD ) VALUES ( 
'FCT_ASSETS', 'PAYSUM', 'Field7', 1); 
INSERT INTO BP_TABLEDEF ( TBLNAME, FLDNAME, FLDNAMEDBF, UNLOAD ) VALUES ( 
'FCT_ASSETS', 'BALSUM', 'Field8', 1); 
INSERT INTO BP_TABLEDEF ( TBLNAME, FLDNAME, FLDNAMEDBF, UNLOAD ) VALUES ( 
'FCT_ASSETS', 'IS_REVALUE', 'Field9', 1); 
INSERT INTO BP_TABLEDEF ( TBLNAME, FLDNAME, FLDNAMEDBF, UNLOAD ) VALUES ( 
'FCT_ASSETS', 'AMORDATE_YEAR', 'Field10', 1); 
INSERT INTO BP_TABLEDEF ( TBLNAME, FLDNAME, FLDNAMEDBF, UNLOAD ) VALUES ( 
'FCT_ASSETS', 'AMORLEVEL_PROC', 'Field11', 1); 
INSERT INTO BP_TABLEDEF ( TBLNAME, FLDNAME, FLDNAMEDBF, UNLOAD ) VALUES ( 
'FCT_ASSETS', 'DT', 'Field12', 1); 
INSERT INTO BP_TABLEDEF ( TBLNAME, FLDNAME, FLDNAMEDBF, UNLOAD ) VALUES ( 
'FCT_ASSETS', 'TYPEASSETS_CODE', 'Field13', 1); 
INSERT INTO BP_TABLEDEF ( TBLNAME, FLDNAME, FLDNAMEDBF, UNLOAD ) VALUES ( 
'FCT_ASSETS', 'PAYCURRENCY_CURR_CODE_TXT', 'Field14', 1); 
INSERT INTO BP_TABLEDEF ( TBLNAME, FLDNAME, FLDNAMEDBF, UNLOAD ) VALUES ( 
'FCT_ASSETS', 'CFA_CODE', 'Field15', 1); 
INSERT INTO BP_TABLEDEF ( TBLNAME, FLDNAME, FLDNAMEDBF, UNLOAD ) VALUES ( 
'FCT_ASSETS', 'REC_STATUS', 'Field16', 1); 
INSERT INTO BP_TABLEDEF ( TBLNAME, FLDNAME, FLDNAMEDBF, UNLOAD ) VALUES ( 
'FCT_ACCOUNT', 'DT', 'Field1', 1); 
INSERT INTO BP_TABLEDEF ( TBLNAME, FLDNAME, FLDNAMEDBF, UNLOAD ) VALUES ( 
'FCT_ACCOUNT', 'REST_NAT', 'Field2', 1); 
INSERT INTO BP_TABLEDEF ( TBLNAME, FLDNAME, FLDNAMEDBF, UNLOAD ) VALUES ( 
'FCT_ACCOUNT', 'DEBET', 'Field3', 1); 
INSERT INTO BP_TABLEDEF ( TBLNAME, FLDNAME, FLDNAMEDBF, UNLOAD ) VALUES ( 
'FCT_ACCOUNT', 'DEBET_NAT', 'Field4', 1); 
INSERT INTO BP_TABLEDEF ( TBLNAME, FLDNAME, FLDNAMEDBF, UNLOAD ) VALUES ( 
'FCT_ACCOUNT', 'CREDIT', 'Field5', 1); 
INSERT INTO BP_TABLEDEF ( TBLNAME, FLDNAME, FLDNAMEDBF, UNLOAD ) VALUES ( 
'FCT_ACCOUNT', 'CREDIT_NAT', 'Field6', 1); 
INSERT INTO BP_TABLEDEF ( TBLNAME, FLDNAME, FLDNAMEDBF, UNLOAD ) VALUES ( 
'FCT_ACCOUNT', 'ACCOUNT_CODE', 'Field7', 1); 
INSERT INTO BP_TABLEDEF ( TBLNAME, FLDNAME, FLDNAMEDBF, UNLOAD ) VALUES ( 
'FCT_ACCOUNT', 'REC_STATUS', 'Field8', 1); 
INSERT INTO BP_TABLEDEF ( TBLNAME, FLDNAME, FLDNAMEDBF, UNLOAD ) VALUES ( 
'FCT_ACCOUNT', 'REST', 'Field9', 1); 
INSERT INTO BP_TABLEDEF ( TBLNAME, FLDNAME, FLDNAMEDBF, UNLOAD ) VALUES ( 
'FCT_ASSETS', 'ACCOUNT', 'ACCOUNT', 0); 
INSERT INTO BP_TABLEDEF ( TBLNAME, FLDNAME, FLDNAMEDBF, UNLOAD ) VALUES ( 
'ASS_ACCOUNT_ASSETS', 'DT', 'Field1', 1); 
INSERT INTO BP_TABLEDEF ( TBLNAME, FLDNAME, FLDNAMEDBF, UNLOAD ) VALUES ( 
'ASS_ACCOUNT_ASSETS', 'ACCOUNT_CODE', 'Field2', 1); 
INSERT INTO BP_TABLEDEF ( TBLNAME, FLDNAME, FLDNAMEDBF, UNLOAD ) VALUES ( 
'ASS_ACCOUNT_ASSETS', 'ASSETS_CODE', 'Field3', 1); 
INSERT INTO BP_TABLEDEF ( TBLNAME, FLDNAME, FLDNAMEDBF, UNLOAD ) VALUES ( 
'ASS_ACCOUNT_ASSETS', 'REC_STATUS', 'Field4', 1); 
INSERT INTO BP_TABLEDEF ( TBLNAME, FLDNAME, FLDNAMEDBF, UNLOAD ) VALUES ( 
'ASS_CARRYPAYMENT', 'DT', 'Field4', 1); 
INSERT INTO BP_TABLEDEF ( TBLNAME, FLDNAME, FLDNAMEDBF, UNLOAD ) VALUES ( 
'ASS_CARRYPAYMENT', 'PAYMENT_CODE', 'Field1', 1); 
INSERT INTO BP_TABLEDEF ( TBLNAME, FLDNAME, FLDNAMEDBF, UNLOAD ) VALUES ( 
'ASS_CARRYPAYMENT', 'CARRY_CODE', 'Field2', 1); 
INSERT INTO BP_TABLEDEF ( TBLNAME, FLDNAME, FLDNAMEDBF, UNLOAD ) VALUES ( 
'ASS_CARRYPAYMENT', 'REC_STATUS', 'Field3', 1); 
INSERT INTO BP_TABLEDEF ( TBLNAME, FLDNAME, FLDNAMEDBF, UNLOAD ) VALUES ( 
'ASS_CFA_ACCOUNT', 'DT', 'Field1', 1); 
INSERT INTO BP_TABLEDEF ( TBLNAME, FLDNAME, FLDNAMEDBF, UNLOAD ) VALUES ( 
'ASS_CFA_ACCOUNT', 'CFA_CODE', 'Field2', 1); 
INSERT INTO BP_TABLEDEF ( TBLNAME, FLDNAME, FLDNAMEDBF, UNLOAD ) VALUES ( 
'ASS_CFA_ACCOUNT', 'ACCOUNT_CODE', 'Field3', 1); 
INSERT INTO BP_TABLEDEF ( TBLNAME, FLDNAME, FLDNAMEDBF, UNLOAD ) VALUES ( 
'ASS_CFA_ACCOUNT', 'REC_STATUS', 'Field4', 1); 
INSERT INTO BP_TABLEDEF ( TBLNAME, FLDNAME, FLDNAMEDBF, UNLOAD ) VALUES ( 
'FCT_BALANCE_CFA', 'REST', 'Field1', 1); 
INSERT INTO BP_TABLEDEF ( TBLNAME, FLDNAME, FLDNAMEDBF, UNLOAD ) VALUES ( 
'FCT_BALANCE_CFA', 'REST_NAT', 'Field2', 1); 
INSERT INTO BP_TABLEDEF ( TBLNAME, FLDNAME, FLDNAMEDBF, UNLOAD ) VALUES ( 
'FCT_BALANCE_CFA', 'REST_OUT', 'Field3', 1); 
INSERT INTO BP_TABLEDEF ( TBLNAME, FLDNAME, FLDNAMEDBF, UNLOAD ) VALUES ( 
'FCT_BALANCE_CFA', 'REST_NAT_OUT', 'Field4', 1); 
INSERT INTO BP_TABLEDEF ( TBLNAME, FLDNAME, FLDNAMEDBF, UNLOAD ) VALUES ( 
'FCT_BALANCE_CFA', 'DEBET', 'Field5', 1); 
INSERT INTO BP_TABLEDEF ( TBLNAME, FLDNAME, FLDNAMEDBF, UNLOAD ) VALUES ( 
'FCT_BALANCE_CFA', 'DEBET_NAT', 'Field6', 1); 
INSERT INTO BP_TABLEDEF ( TBLNAME, FLDNAME, FLDNAMEDBF, UNLOAD ) VALUES ( 
'FCT_BALANCE_CFA', 'CREDIT', 'Field7', 1); 
INSERT INTO BP_TABLEDEF ( TBLNAME, FLDNAME, FLDNAMEDBF, UNLOAD ) VALUES ( 
'FCT_BALANCE_CFA', 'CREDIT_NAT', 'Field8', 1); 
INSERT INTO BP_TABLEDEF ( TBLNAME, FLDNAME, FLDNAMEDBF, UNLOAD ) VALUES ( 
'FCT_BALANCE_CFA', 'DT', 'Field9', 1); 
INSERT INTO BP_TABLEDEF ( TBLNAME, FLDNAME, FLDNAMEDBF, UNLOAD ) VALUES ( 
'FCT_BALANCE_CFA', 'BALANCE_CODE', 'Field10', 1); 
INSERT INTO BP_TABLEDEF ( TBLNAME, FLDNAME, FLDNAMEDBF, UNLOAD ) VALUES ( 
'FCT_BALANCE_CFA', 'BALANCE_CHAPTER_CODE', 'Field11', 1); 
INSERT INTO BP_TABLEDEF ( TBLNAME, FLDNAME, FLDNAMEDBF, UNLOAD ) VALUES ( 
'FCT_BALANCE_CFA', 'BALANCE_PLAN_BAL_CODE', 'Field12', 1); 
INSERT INTO BP_TABLEDEF ( TBLNAME, FLDNAME, FLDNAMEDBF, UNLOAD ) VALUES ( 
'FCT_BALANCE_CFA', 'CFA_CODE', 'Field13', 1); 
INSERT INTO BP_TABLEDEF ( TBLNAME, FLDNAME, FLDNAMEDBF, UNLOAD ) VALUES ( 
'FCT_BALANCE_CFA', 'CURRENCY_CURR_CODE_TXT', 'Field14', 1); 
INSERT INTO BP_TABLEDEF ( TBLNAME, FLDNAME, FLDNAMEDBF, UNLOAD ) VALUES ( 
'FCT_BALANCE_CFA', 'DEPARTMENT_CODE', 'Field15', 1); 
INSERT INTO BP_TABLEDEF ( TBLNAME, FLDNAME, FLDNAMEDBF, UNLOAD ) VALUES ( 
'FCT_BALANCE_CFA', 'REC_STATUS', 'Field16', 1); 
INSERT INTO BP_TABLEDEF ( TBLNAME, FLDNAME, FLDNAMEDBF, UNLOAD ) VALUES ( 
'ASS_PLAN_DEP', 'DT', 'Field1', 1); 
INSERT INTO BP_TABLEDEF ( TBLNAME, FLDNAME, FLDNAMEDBF, UNLOAD ) VALUES ( 
'ASS_PLAN_DEP', 'DEPARTMENT_CODE', 'FIeld2', 1); 
INSERT INTO BP_TABLEDEF ( TBLNAME, FLDNAME, FLDNAMEDBF, UNLOAD ) VALUES ( 
'ASS_PLAN_DEP', 'PLAN_BAL_CODE', 'Field3', 1); 
INSERT INTO BP_TABLEDEF ( TBLNAME, FLDNAME, FLDNAMEDBF, UNLOAD ) VALUES ( 
'ASS_PLAN_DEP', 'REC_STATUS', 'Field4', 1); 
INSERT INTO BP_TABLEDEF ( TBLNAME, FLDNAME, FLDNAMEDBF, UNLOAD ) VALUES ( 
'ASS_PLAN_DEP', 'SYSMOMENT', 'Field5', 1); 
INSERT INTO BP_TABLEDEF ( TBLNAME, FLDNAME, FLDNAMEDBF, UNLOAD ) VALUES ( 
'FCT_BALANCE_CFA', 'SYSMOMENT', 'Field17', 1); 
INSERT INTO BP_TABLEDEF ( TBLNAME, FLDNAME, FLDNAMEDBF, UNLOAD ) VALUES ( 
'FCT_HALFCARRY', 'SYSMOMENT', 'Field10', 1); 
INSERT INTO BP_TABLEDEF ( TBLNAME, FLDNAME, FLDNAMEDBF, UNLOAD ) VALUES ( 
'FCT_REVAL', 'CODE', 'Field1', 1); 
INSERT INTO BP_TABLEDEF ( TBLNAME, FLDNAME, FLDNAMEDBF, UNLOAD ) VALUES ( 
'FCT_REVAL', 'DT', 'Field2', 1); 
INSERT INTO BP_TABLEDEF ( TBLNAME, FLDNAME, FLDNAMEDBF, UNLOAD ) VALUES ( 
'FCT_REVAL', 'REVAL_SUM', 'Field3', 1); 
INSERT INTO BP_TABLEDEF ( TBLNAME, FLDNAME, FLDNAMEDBF, UNLOAD ) VALUES ( 
'FCT_REVAL', 'HALFCARRY_CODE', 'Field4', 1); 
INSERT INTO BP_TABLEDEF ( TBLNAME, FLDNAME, FLDNAMEDBF, UNLOAD ) VALUES ( 
'FCT_REVAL', 'ACCOUNT_CODE', 'Field5', 1); 
INSERT INTO BP_TABLEDEF ( TBLNAME, FLDNAME, FLDNAMEDBF, UNLOAD ) VALUES ( 
'FCT_REVAL', 'REC_STATUS', 'Field6', 1); 
INSERT INTO BP_TABLEDEF ( TBLNAME, FLDNAME, FLDNAMEDBF, UNLOAD ) VALUES ( 
'FCT_REVAL', 'SYSMOMENT', 'Field7', 1); 
INSERT INTO BP_TABLEDEF ( TBLNAME, FLDNAME, FLDNAMEDBF, UNLOAD ) VALUES ( 
'FCT_SUBJATTR', 'ATTRVALUE', 'Field1', 1); 
INSERT INTO BP_TABLEDEF ( TBLNAME, FLDNAME, FLDNAMEDBF, UNLOAD ) VALUES ( 
'FCT_SUBJATTR', 'DT', 'Field2', 1); 
INSERT INTO BP_TABLEDEF ( TBLNAME, FLDNAME, FLDNAMEDBF, UNLOAD ) VALUES ( 
'FCT_SUBJATTR', 'SUBJECT_CODE', 'Field3', 1); 
INSERT INTO BP_TABLEDEF ( TBLNAME, FLDNAME, FLDNAMEDBF, UNLOAD ) VALUES ( 
'ASS_SUBJECT_CAT', 'SYSMOMENT', 'Field6', 1); 
INSERT INTO BP_TABLEDEF ( TBLNAME, FLDNAME, FLDNAMEDBF, UNLOAD ) VALUES ( 
'FCT_SUBJATTR', 'TYPEATTR_CODE', 'Field4', 1); 
INSERT INTO BP_TABLEDEF ( TBLNAME, FLDNAME, FLDNAMEDBF, UNLOAD ) VALUES ( 
'FCT_SUBJATTR', 'DEPARTMENT_CODE', 'Field5', 1); 
INSERT INTO BP_TABLEDEF ( TBLNAME, FLDNAME, FLDNAMEDBF, UNLOAD ) VALUES ( 
'FCT_SUBJATTR', 'SYSTEM_CODE', 'Field6', 1); 
INSERT INTO BP_TABLEDEF ( TBLNAME, FLDNAME, FLDNAMEDBF, UNLOAD ) VALUES ( 
'FCT_SUBJATTR', 'REC_STATUS', 'Field7', 1); 
INSERT INTO BP_TABLEDEF ( TBLNAME, FLDNAME, FLDNAMEDBF, UNLOAD ) VALUES ( 
'FCT_SUBJATTR', 'SYSMOMENT', 'Field8', 1); 
INSERT INTO BP_TABLEDEF ( TBLNAME, FLDNAME, FLDNAMEDBF, UNLOAD ) VALUES ( 
'DET_ACCOUNT', 'SYSMOMENT', 'Field15', 1); 
INSERT INTO BP_TABLEDEF ( TBLNAME, FLDNAME, FLDNAMEDBF, UNLOAD ) VALUES ( 
'DET_JURIDIC_PERSON', 'SYSMOMENT', 'Field8', 1); 
INSERT INTO BP_TABLEDEF ( TBLNAME, FLDNAME, FLDNAMEDBF, UNLOAD ) VALUES ( 
'ASS_ACCOUNT_BALANCE', 'SYSMOMENT', 'Field7', 1); 
INSERT INTO BP_TABLEDEF ( TBLNAME, FLDNAME, FLDNAMEDBF, UNLOAD ) VALUES ( 
'ASS_ACCOUNT_CAT', 'DT', 'Field1', 1); 
INSERT INTO BP_TABLEDEF ( TBLNAME, FLDNAME, FLDNAMEDBF, UNLOAD ) VALUES ( 
'DET_PHYZ_PERSON', 'SYSMOMENT', 'Field10', 1); 
INSERT INTO BP_TABLEDEF ( TBLNAME, FLDNAME, FLDNAMEDBF, UNLOAD ) VALUES ( 
'ASS_ACCOUNT_CAT', 'ACCOUNT_CODE', 'Field2', 1); 
INSERT INTO BP_TABLEDEF ( TBLNAME, FLDNAME, FLDNAMEDBF, UNLOAD ) VALUES ( 
'ASS_ACCOUNT_CAT', 'ACCOUNT_CAT_VAL_CODE', 'Field3', 1); 
INSERT INTO BP_TABLEDEF ( TBLNAME, FLDNAME, FLDNAMEDBF, UNLOAD ) VALUES ( 
'DET_SUBJECT', 'SYSMOMENT', 'Field11', 1); 
INSERT INTO BP_TABLEDEF ( TBLNAME, FLDNAME, FLDNAMEDBF, UNLOAD ) VALUES ( 
'ASS_ACCOUNT_CAT', 'ACCOUNT_CAT_VAL_ACCOUNT_CAT_CO', 'Field4', 1); 
INSERT INTO BP_TABLEDEF ( TBLNAME, FLDNAME, FLDNAMEDBF, UNLOAD ) VALUES ( 
'ASS_ACCOUNT_CAT', 'REC_STATUS', 'Field5', 1); 
INSERT INTO BP_TABLEDEF ( TBLNAME, FLDNAME, FLDNAMEDBF, UNLOAD ) VALUES ( 
'ASS_ACCOUNT_CAT', 'SYSMOMENT', 'Field6', 1); 
INSERT INTO BP_TABLEDEF ( TBLNAME, FLDNAME, FLDNAMEDBF, UNLOAD ) VALUES ( 
'ASS_CARRY_CAT', 'CARRY_CAT_VAL_CODE', 'Field2', 1); 
INSERT INTO BP_TABLEDEF ( TBLNAME, FLDNAME, FLDNAMEDBF, UNLOAD ) VALUES ( 
'ASS_CARRY_CAT', 'CARRY_CAT_VAL_CARRY_CAT_CODE', 'Field3', 1); 
INSERT INTO BP_TABLEDEF ( TBLNAME, FLDNAME, FLDNAMEDBF, UNLOAD ) VALUES ( 
'FCT_ACCOUNT', 'SYSMOMENT', 'Field10', 1); 
INSERT INTO BP_TABLEDEF ( TBLNAME, FLDNAME, FLDNAMEDBF, UNLOAD ) VALUES ( 
'ASS_CARRY_CAT', 'DT', 'Field1', 1); 
INSERT INTO BP_TABLEDEF ( TBLNAME, FLDNAME, FLDNAMEDBF, UNLOAD ) VALUES ( 
'ASS_CARRY_CAT', 'CARRY_CODE', 'Field4', 1); 
INSERT INTO BP_TABLEDEF ( TBLNAME, FLDNAME, FLDNAMEDBF, UNLOAD ) VALUES ( 
'ASS_CARRY_CAT', 'REC_STATUS', 'Field5', 1); 
INSERT INTO BP_TABLEDEF ( TBLNAME, FLDNAME, FLDNAMEDBF, UNLOAD ) VALUES ( 
'ASS_CARRY_CAT', 'SYSMOMENT', 'Field6', 1); 
INSERT INTO BP_TABLEDEF ( TBLNAME, FLDNAME, FLDNAMEDBF, UNLOAD ) VALUES ( 
'ASS_CFA_ACCOUNT', 'SYSMOMENT', 'Field5', 1); 
INSERT INTO BP_TABLEDEF ( TBLNAME, FLDNAME, FLDNAMEDBF, UNLOAD ) VALUES ( 
'ASS_HALFCARRY_CAT', 'DT', 'Field1', 1); 
INSERT INTO BP_TABLEDEF ( TBLNAME, FLDNAME, FLDNAMEDBF, UNLOAD ) VALUES ( 
'ASS_HALFCARRY_CAT', 'CARRY_CAT_VAL_CODE', 'Field2', 1); 
INSERT INTO BP_TABLEDEF ( TBLNAME, FLDNAME, FLDNAMEDBF, UNLOAD ) VALUES ( 
'ASS_HALFCARRY_CAT', 'CARRY_CAT_VAL_CARRY_CAT_CODE', 'Field3', 1); 
INSERT INTO BP_TABLEDEF ( TBLNAME, FLDNAME, FLDNAMEDBF, UNLOAD ) VALUES ( 
'ASS_HALFCARRY_CAT', 'HALFCARRY_CODE', 'Field4', 1); 
INSERT INTO BP_TABLEDEF ( TBLNAME, FLDNAME, FLDNAMEDBF, UNLOAD ) VALUES ( 
'ASS_HALFCARRY_CAT', 'REC_STATUS', 'Field5', 1); 
INSERT INTO BP_TABLEDEF ( TBLNAME, FLDNAME, FLDNAMEDBF, UNLOAD ) VALUES ( 
'ASS_HALFCARRY_CAT', 'SYSMOMENT', 'Field6', 1); 
INSERT INTO BP_TABLEDEF ( TBLNAME, FLDNAME, FLDNAMEDBF, UNLOAD ) VALUES ( 
'FCT_PAYMENT', 'RECACCOUNT_CODE', 'Field11', 1); 
INSERT INTO BP_TABLEDEF ( TBLNAME, FLDNAME, FLDNAMEDBF, UNLOAD ) VALUES ( 
'FCT_PAYMENT', 'PAYACCOUNT_CODE', 'Field12', 1); 
INSERT INTO BP_TABLEDEF ( TBLNAME, FLDNAME, FLDNAMEDBF, UNLOAD ) VALUES ( 
'FCT_PAYMENT', 'REC_STATUS', 'Field13', 1); 
INSERT INTO BP_TABLEDEF ( TBLNAME, FLDNAME, FLDNAMEDBF, UNLOAD ) VALUES ( 
'FCT_PAYMENT', 'DT', 'Field14', 1); 
INSERT INTO BP_TABLEDEF ( TBLNAME, FLDNAME, FLDNAMEDBF, UNLOAD ) VALUES ( 
'FCT_PAYMENT', 'CODE', 'Field15', 1); 
INSERT INTO BP_TABLEDEF ( TBLNAME, FLDNAME, FLDNAMEDBF, UNLOAD ) VALUES ( 
'FCT_PAYMENT', 'TYPEPAYMENT', 'Field16', 1); 
INSERT INTO BP_TABLEDEF ( TBLNAME, FLDNAME, FLDNAMEDBF, UNLOAD ) VALUES ( 
'FCT_PAYMENT', 'SYSMOMENT', 'Field17', 1); 
INSERT INTO BP_TABLEDEF ( TBLNAME, FLDNAME, FLDNAMEDBF, UNLOAD ) VALUES ( 
'FCT_CLPAYMENT', 'PAYMENT_CODE', 'Field20', 1); 
INSERT INTO BP_TABLEDEF ( TBLNAME, FLDNAME, FLDNAMEDBF, UNLOAD ) VALUES ( 
'FCT_CLPAYMENT', 'SYSMOMENT', 'Field22', 1); 
INSERT INTO BP_TABLEDEF ( TBLNAME, FLDNAME, FLDNAMEDBF, UNLOAD ) VALUES ( 
'FCT_ASSETS', 'SYSMOMENT', 'Field17', 1); 
INSERT INTO BP_TABLEDEF ( TBLNAME, FLDNAME, FLDNAMEDBF, UNLOAD ) VALUES ( 
'ASS_ACCOUNT_ASSETS', 'SYSMOMENT', 'Field5', 1); 
INSERT INTO BP_TABLEDEF ( TBLNAME, FLDNAME, FLDNAMEDBF, UNLOAD ) VALUES ( 
'ASS_CARRYPAYMENT', 'SYSMOMENT', 'Field5', 1); 
INSERT INTO BP_TABLEDEF ( TBLNAME, FLDNAME, FLDNAMEDBF, UNLOAD ) VALUES ( 
'ASS_ACCOUNT_BALANCE', 'BALANCE_CHAPTER_CODE', 'Field4', 1); 
Insert into bp_tabledef(TBLNAME, FLDNAME, FLDNAMEDBF, UNLOAD)
 Values('ASS_HALFCARRY_ACCOUNT_CORR', 'DT', 'Field1', 1);
Insert into bp_tabledef(TBLNAME, FLDNAME, FLDNAMEDBF, UNLOAD)
 Values('ASS_HALFCARRY_ACCOUNT_CORR', 'HALFCARRY_CODE', 'Field3', 1);
Insert into bp_tabledef(TBLNAME, FLDNAME, FLDNAMEDBF, UNLOAD)
 Values('ASS_HALFCARRY_ACCOUNT_CORR', 'ACCOUNT_CODE', 'Field4', 1);
Insert into bp_tabledef(TBLNAME, FLDNAME, FLDNAMEDBF, UNLOAD)
 Values('ASS_HALFCARRY_ACCOUNT_CORR', 'SYSMOMENT', 'Field2', 1);
Insert into bp_tabledef(TBLNAME, FLDNAME, FLDNAMEDBF, UNLOAD)
 Values('ASS_HALFCARRY_ACCOUNT_CORR', 'REC_STATUS', 'Field5', 1);
commit;
 
